SELECT
		*
FROM	(
			SELECT
					ROW_NUMBER() OVER( ORDER BY XX.INDATE DESC ) AS ROWNUM ,
					XX.*
			FROM	(
						SELECT
								COH.* ,
								( SELECT USER_NM FROM O_USER WHERE RTRIM(USERID) = RTRIM(COH.USERID)) AS USER_NM ,
								CU.CUST_NM , ST.SHIPTO_NM , US_SALES.USERID AS SALESUSERID, US_SALES.USER_NM AS SALESUSER_NM ,
								( SELECT CSUSERID FROM O_CSSALESMAP WHERE SALESUSERID = US_SALES.USERID AND FIXEDYN = 'Y') AS CSUSERID ,
								( SELECT SUB1.USER_NM FROM O_USER SUB1, O_CSSALESMAP SUB2 WHERE SUB1.USERID = SUB2.CSUSERID AND SUB2.SALESUSERID = US_SALES.USERID AND SUB2.FIXEDYN = 'Y') AS CSUSER_NM ,
								( SELECT COUNT(*) FROM O_CUST_ORDER_D WHERE REQ_NO = COH.REQ_NO) AS ITEM_CNT ,
								( SELECT TOP 1 CONFIRM_DT FROM O_ORDER_CONFIRM_H WHERE REQ_NO = COH.REQ_NO) AS CONFIRM_DT2 ,
								QM.QMS_TEMP_ID
						FROM	O_CUST_ORDER_H COH
								LEFT OUTER JOIN QMS_PRE_MAST QM
										ON QM.REQ_NO = COH.REQ_NO AND QM.DELETEYN = 'N'
								LEFT JOIN O_CUSTOMER CU
										ON COH.CUST_CD = CU.CUST_CD
								LEFT JOIN O_SHIPTO ST
										ON COH.SHIPTO_CD = ST.SHIPTO_CD
								LEFT JOIN O_USER US_SALES
										ON CU.SALESREP_CD = US_SALES.USERID
						WHERE	COH.INDATE >= CONVERT(DATE, '2024-10-18') AND COH.INDATE < DATEADD(day, 1, CONVERT(DATE, '2024-10-18'))
						AND		COH.STATUS_CD IN ('00')
					) XX
		) S
WHERE	ROWNUM BETWEEN 1 AND 10
;




SELECT
		*
FROM	(
			SELECT
					ROW_NUMBER() OVER( ORDER BY XX.INDATE DESC ) AS ROWNUM ,
					XX.*
			FROM	(
						SELECT
								COH.* ,
								( SELECT USER_NM FROM O_USER WHERE RTRIM(USERID) = RTRIM(COH.USERID) ) AS USER_NM ,
								CU.CUST_NM , ST.SHIPTO_NM , US_SALES.USERID AS SALESUSERID, US_SALES.USER_NM AS SALESUSER_NM ,
								(SELECT CSUSERID FROM O_CSSALESMAP WHERE SALESUSERID = US_SALES.USERID AND FIXEDYN = 'Y') AS CSUSERID ,
								(SELECT SUB1.USER_NM FROM O_USER SUB1, O_CSSALESMAP SUB2 WHERE SUB1.USERID = SUB2.CSUSERID AND SUB2.SALESUSERID = US_SALES.USERID AND SUB2.FIXEDYN = 'Y') AS CSUSER_NM ,
								(SELECT COUNT(*) FROM O_CUST_ORDER_D WHERE REQ_NO = COH.REQ_NO) AS ITEM_CNT ,
								( SELECT TOP 1 CONFIRM_DT FROM O_ORDER_CONFIRM_H WHERE REQ_NO = COH.REQ_NO) AS CONFIRM_DT2 ,
								QM.QMS_TEMP_ID
						FROM	O_CUST_ORDER_H COH
								LEFT OUTER JOIN QMS_PRE_MAST QM
										ON QM.REQ_NO = COH.REQ_NO
										AND QM.DELETEYN = 'N'
								LEFT JOIN O_CUSTOMER CU
										ON COH.CUST_CD = CU.CUST_CD
								LEFT JOIN O_SHIPTO ST
										ON COH.SHIPTO_CD = ST.SHIPTO_CD
								LEFT JOIN O_USER US_SALES
										ON CU.SALESREP_CD = US_SALES.USERID
								WHERE	COH.INDATE >= CONVERT(DATE, '2024-10-18')
								AND COH.INDATE < DATEADD(day, 1, CONVERT(DATE, '2024-10-18'))
					) XX
		) S
	WHERE	ROWNUM BETWEEN 1 AND 10

;



SELECT dbo.SF_GETQMSID_SEQ(3) AS NEW_QMS_ID;


-- INSERT INTO QMS_ORD_FRCN	(QMS_ID, QMS_SEQ, QMS_FRCN_ID, KEYCODE, CREATEUSER, CREATETIME, UPDATEUSER, UPDATETIME, DELETEYN)
SELECT
		'20241Q0099', 1, QMS_FRCN_ID, KEYCODE, CREATEUSER, CREATETIME, UPDATEUSER, UPDATETIME, DELETEYN
FROM	QMS_ORD_FRCN QOF
WHERE	EXISTS	(
					SELECT	*
					FROM	QMS_ORD_MAST A , QMS_ORD_DETL B , QMS_SALESORDER C
					WHERE	A.QMS_ID = B.QMS_ID
					AND		A.QMS_SEQ = B.QMS_SEQ
					AND		QOF.QMS_ID = A.QMS_ID
					AND		QOR.QMS_SEQ = A.QMS_SEQ
					AND		A.DELETEYN = 'N'
					AND		B.DELETEYN = 'N'
					AND		B.ORDERNO = C.ORDERNO
					AND		B.LINE_NO = C.LINE_NO
					AND		A.CUST_CD = '10172665'
					AND		C.SHIPTO_CD = '9005263181'
					GROUP BY A.CUST_CD, C.SHIPTO_CD
				)



WHERE	(QMS_ID, QMS_SEQ) IN (
								SELECT
										QMS_ID, QMS_SEQ
								FROM	(
											SELECT
													RANK() OVER(PARTITION BY A.CUST_CD, C.SHIPTO_CD ORDER BY A.QMS_ID DESC, A.QMS_SEQ DESC, B.QMS_DETL_ID DESC) AS RNUM ,
													A.*
											FROM	QMS_ORD_MAST A , QMS_ORD_DETL B , QMS_SALESORDER C
											WHERE	A.QMS_ID = B.QMS_ID
											AND		A.QMS_SEQ = B.QMS_SEQ
											AND		A.DELETEYN = 'N'
											AND		B.DELETEYN = 'N'
											AND		B.ORDERNO = C.ORDERNO
											AND		B.LINE_NO = C.LINE_NO
											AND		A.CUST_CD = ?
											AND		C.SHIPTO_CD = ?
										)
								WHERE	RNUM = 1
							)

;
--20241Q0099(String), 1(String), 10172665(String), 9005263181(String), 부산 북항 초고층복합개발사업-롯데(String), admin(String), admin(String), T(String)






















