SELECT
		*
FROM	(
			SELECT
					ROW_NUMBER() OVER( ORDER BY XX.INDATE DESC ) AS ROWNUM ,
					XX.*
			FROM	(
						SELECT
								COH.* ,
								( SELECT USER_NM FROM O_USER WHERE RTRIM(USERID) = RTRIM(COH.USERID)) AS USER_NM ,
								CU.CUST_NM , ST.SHIPTO_NM , US_SALES.USERID AS SALESUSERID, US_SALES.USER_NM AS SALESUSER_NM ,
								( SELECT CSUSERID FROM O_CSSALESMAP WHERE SALESUSERID = US_SALES.USERID AND FIXEDYN = 'Y') AS CSUSERID ,
								( SELECT SUB1.USER_NM FROM O_USER SUB1, O_CSSALESMAP SUB2 WHERE SUB1.USERID = SUB2.CSUSERID AND SUB2.SALESUSERID = US_SALES.USERID AND SUB2.FIXEDYN = 'Y') AS CSUSER_NM ,
								( SELECT COUNT(*) FROM O_CUST_ORDER_D WHERE REQ_NO = COH.REQ_NO) AS ITEM_CNT ,
								( SELECT TOP 1 CONFIRM_DT FROM O_ORDER_CONFIRM_H WHERE REQ_NO = COH.REQ_NO) AS CONFIRM_DT2 ,
								QM.QMS_TEMP_ID
						FROM	O_CUST_ORDER_H COH
								LEFT OUTER JOIN QMS_PRE_MAST QM
										ON QM.REQ_NO = COH.REQ_NO AND QM.DELETEYN = 'N'
								LEFT JOIN O_CUSTOMER CU
										ON COH.CUST_CD = CU.CUST_CD
								LEFT JOIN O_SHIPTO ST
										ON COH.SHIPTO_CD = ST.SHIPTO_CD
								LEFT JOIN O_USER US_SALES
										ON CU.SALESREP_CD = US_SALES.USERID
						WHERE	COH.INDATE >= CONVERT(DATE, '2024-10-18') AND COH.INDATE < DATEADD(day, 1, CONVERT(DATE, '2024-10-18'))
						AND		COH.STATUS_CD IN ('00')
					) XX
		) S
WHERE	ROWNUM BETWEEN 1 AND 10
;




SELECT
		*
FROM	(
			SELECT
					ROW_NUMBER() OVER( ORDER BY XX.INDATE DESC ) AS ROWNUM ,
					XX.*
			FROM	(
						SELECT
								COH.* ,
								( SELECT USER_NM FROM O_USER WHERE RTRIM(USERID) = RTRIM(COH.USERID) ) AS USER_NM ,
								CU.CUST_NM , ST.SHIPTO_NM , US_SALES.USERID AS SALESUSERID, US_SALES.USER_NM AS SALESUSER_NM ,
								(SELECT CSUSERID FROM O_CSSALESMAP WHERE SALESUSERID = US_SALES.USERID AND FIXEDYN = 'Y') AS CSUSERID ,
								(SELECT SUB1.USER_NM FROM O_USER SUB1, O_CSSALESMAP SUB2 WHERE SUB1.USERID = SUB2.CSUSERID AND SUB2.SALESUSERID = US_SALES.USERID AND SUB2.FIXEDYN = 'Y') AS CSUSER_NM ,
								(SELECT COUNT(*) FROM O_CUST_ORDER_D WHERE REQ_NO = COH.REQ_NO) AS ITEM_CNT ,
								( SELECT TOP 1 CONFIRM_DT FROM O_ORDER_CONFIRM_H WHERE REQ_NO = COH.REQ_NO) AS CONFIRM_DT2 ,
								QM.QMS_TEMP_ID
						FROM	O_CUST_ORDER_H COH
								LEFT OUTER JOIN QMS_PRE_MAST QM
										ON QM.REQ_NO = COH.REQ_NO
										AND QM.DELETEYN = 'N'
								LEFT JOIN O_CUSTOMER CU
										ON COH.CUST_CD = CU.CUST_CD
								LEFT JOIN O_SHIPTO ST
										ON COH.SHIPTO_CD = ST.SHIPTO_CD
								LEFT JOIN O_USER US_SALES
										ON CU.SALESREP_CD = US_SALES.USERID
								WHERE	COH.INDATE >= CONVERT(DATE, '2024-10-18')
								AND COH.INDATE < DATEADD(day, 1, CONVERT(DATE, '2024-10-18'))
					) XX
		) S
	WHERE	ROWNUM BETWEEN 1 AND 10

;



SELECT dbo.SF_GETQMSID_SEQ(3) AS NEW_QMS_ID;


-- INSERT INTO QMS_ORD_FRCN	(QMS_ID, QMS_SEQ, QMS_FRCN_ID, KEYCODE, CREATEUSER, CREATETIME, UPDATEUSER, UPDATETIME, DELETEYN)
SELECT
		'20241Q0099', 1, QMS_FRCN_ID, KEYCODE, CREATEUSER, CREATETIME, UPDATEUSER, UPDATETIME, DELETEYN
FROM	QMS_ORD_FRCN QOF
WHERE	EXISTS	(
					SELECT	*
					FROM	QMS_ORD_MAST A , QMS_ORD_DETL B , QMS_SALESORDER C
					WHERE	A.QMS_ID = B.QMS_ID
					AND		A.QMS_SEQ = B.QMS_SEQ
					AND		QOF.QMS_ID = A.QMS_ID
					AND		QOF.QMS_SEQ = A.QMS_SEQ
					AND		A.DELETEYN = 'N'
					AND		B.DELETEYN = 'N'
					AND		B.ORDERNO = C.ORDERNO
					AND		B.LINE_NO = C.LINE_NO
					AND		A.CUST_CD = '10172642'
					AND		C.SHIPTO_CD = '0010172642'
				)
;


SELECT * FROM QMS_ORD_FRCN;






					SELECT	A.CUST_CD, C.SHIPTO_CD
					FROM	QMS_ORD_MAST A , QMS_ORD_DETL B , QMS_SALESORDER C
					WHERE	A.QMS_ID = B.QMS_ID
					AND		A.QMS_SEQ = B.QMS_SEQ
					AND		A.DELETEYN = 'N'
					AND		B.DELETEYN = 'N'
					AND		B.ORDERNO = C.ORDERNO
					AND		B.LINE_NO = C.LINE_NO
--					AND		A.CUST_CD = '10172665'
--					AND		C.SHIPTO_CD = '9005263181'
					AND 	EXISTS	(
										SELECT * FROM QMS_ORD_FRCN T WHERE A.QMS_ID = T.QMS_ID AND A.QMS_SEQ = T.QMS_SEQ
									)
					GROUP BY A.CUST_CD, C.SHIPTO_CD



--WHERE	(QMS_ID, QMS_SEQ) IN (
--								SELECT
--										QMS_ID, QMS_SEQ
--								FROM	(
--											SELECT
--													RANK() OVER(PARTITION BY A.CUST_CD, C.SHIPTO_CD ORDER BY A.QMS_ID DESC, A.QMS_SEQ DESC, B.QMS_DETL_ID DESC) AS RNUM ,
--													A.*
--											FROM	QMS_ORD_MAST A , QMS_ORD_DETL B , QMS_SALESORDER C
--											WHERE	A.QMS_ID = B.QMS_ID
--											AND		A.QMS_SEQ = B.QMS_SEQ
--											AND		A.DELETEYN = 'N'
--											AND		B.DELETEYN = 'N'
--											AND		B.ORDERNO = C.ORDERNO
--											AND		B.LINE_NO = C.LINE_NO
--											AND		A.CUST_CD = ?
--											AND		C.SHIPTO_CD = ?
--										)
--								WHERE	RNUM = 1
--							)

;
--20241Q0099(String), 1(String), 10172665(String), 9005263181(String), 부산 북항 초고층복합개발사업-롯데(String), admin(String), admin(String), T(String)








SELECT
	COUNT(*)
FROM
	O_SALESORDER SO
WHERE
	SO.STATUS2 IN (560, 580, 620)
	AND ((SO.STATUS1 = 580
		AND SO.STATUS2 = 620)
--		AND SO.REQUEST_DT < TO_CHAR(SYSDATE, 'yyyymmdd'))
		AND SO.REQUEST_DT < FORMAT(getDate(), 'yyyymmdd'))
	AND SO.ORDERTY <> 'KL'
	AND SO.ORDER_DT >= ?
	AND SO.ORDER_DT <= ?

;






/* eorder.o_qmsorder.list */
SELECT
		/*+ HASH(table) */
		*
FROM	(
			SELECT
					ROW_NUMBER() OVER( ORDER BY XX.ORDERNO DESC, XX.LINE_NO ASC ) AS ROWNUM ,
					XX.* ,
					CASE
						WHEN PRE1 = 'Y' AND PRE2 = 'Y' /* 사전입력 완료 */ THEN '사전'
						WHEN PRE1 = 'Y' AND PRE2 = 'N' /* 사전입력중 */ THEN '사전'
						ELSE '사후' /* 사후입력 대상 */
					END AS QMS_STEP
			FROM	(
						SELECT
								dbo.Sf_getpreorderyn(SO.cust_po) AS PRE1 ,
								dbo.Sf_getpreqtyyn(SO.cust_po) AS PRE2 ,
								ORDERNO, LINE_NO ,
								dbo.SF_GETQMSID(ORDERNO, LINE_NO)AS QMS_ARR ,
								dbo.SF_GETQMSID(ORDERNO, LINE_NO)AS QMS_ARR_TXT ,
								CASE
									WHEN (CONVERT(DECIMAL, dbo.SF_GETPREQTY(SO.cust_po)) >= CONVERT(DECIMAL, SO.ORDER_QTY)
											AND dbo.Sf_getpreorderyn(SO.cust_po) = 'Y'
											AND dbo.Sf_getpreqtyyn(SO.cust_po) = 'Y')
										THEN CONVERT(DECIMAL, SO.ORDER_QTY)
									WHEN dbo.Sf_getpreorderyn(SO.cust_po) = 'Y' THEN CONVERT(DECIMAL, dbo.SF_GETPREQTY(SO.cust_po))
									ELSE CONVERT(DECIMAL, dbo.Sf_getqmsqty(orderno, line_no))
								END AS QMS_ARR_QTY ,
								CASE WHEN ORDER_QTY = dbo.SF_GETQMSQTY(ORDERNO, LINE_NO) THEN '완료' ELSE '미완료' END AS QMS_STATUS ,
								dbo.SF_GETQMSSHIPTO(ORDERNO, LINE_NO)AS QMS_ARR_SHIPTO ,
								dbo.SF_GETMAILYN(ORDERNO, LINE_NO) AS MAIL_YN ,
								dbo.SF_GETFILEYN(ORDERNO, LINE_NO) AS FILE_YN ,
								SO.ITEM_CD , ORDERTY , CUST_PO , CUST_CD , CUST_NM , dbo.SF_GETQMSQUARTER(ACTUAL_SHIP_DT) AS ACTUAL_SHIP_QUARTER ,
								dbo.SF_GETQMSACTIVEYN(dbo.SF_GETQMSQUARTER(ACTUAL_SHIP_DT)) AS ACTIVEYN ,
								CONCAT(CONCAT(CONCAT(CONCAT(SUBSTRING(ORDER_DT, 0, 4), '-'), SUBSTRING(ORDER_DT, 5, 2)), '-'), SUBSTRING(ORDER_DT, 7, 2)) AS ORDER_DT ,
								CONCAT(CONCAT(CONCAT(CONCAT(SUBSTRING(ACTUAL_SHIP_DT, 0, 4), '-'), SUBSTRING(ACTUAL_SHIP_DT, 5, 2)), '-'), SUBSTRING(ACTUAL_SHIP_DT, 7, 2)) AS ACTUAL_SHIP_DT ,
								SHIPTO_CD, SHIPTO_NM, RTRIM(CONCAT(ADD1, ADD2)) AS ADDR, ITEM_DESC, LOTN, ORDER_QTY, UNIT, SALESREP_NM,
								OIN.SALES_CD3
						FROM	qms_salesorder SO
								LEFT JOIN O_ITEM_NEW OIN
										ON OIN.ITEM_CD = SO.ITEM_CD /*2024-09-30 hsg LINE_TY에 'Y'값이 없어 죠회가 되지 않아. LEFT JOIN 시 조건을 걸었음 */
										AND OIN.LINE_TY = 'Y'
--										AND	OIN.SALES_CD3 IN ('DAP11400', 'DAP11500', 'DAP11600', 'DAP11700', 'DAP12400', 'DAP12500', 'DAP12800', 'DAP12900', 'DAP13000')
						WHERE
								/*2024-09-30 hsg LINE_TY에 'Y'값이 없어 죠회가 되지 않아. LEFT JOIN 시로 취치를 옮김 */
								/* AND OIN.LINE_TY = 'Y' */
								1 = 1
						AND		NOT(SO.STATUS1 = '980')
						AND		SO.STATUS2 >= '620'
						AND		SO.ACTUAL_SHIP_DT >= '20240401'
						AND		SO.ACTUAL_SHIP_DT <= '20240630'
--						AND		OIN.SALES_CD3 IN ('DAP11400', 'DAP11500', 'DAP11600', 'DAP11700', 'DAP12400', 'DAP12500', 'DAP12800', 'DAP12900', 'DAP13000')
					) XX
			WHERE	1 = 1
--			AND 	XX.SALES_CD3 IS NOT NULL
			AND		XX.SALES_CD3 IN ('DAP11400', 'DAP11500', 'DAP11600', 'DAP11700', 'DAP12400', 'DAP12500', 'DAP12800', 'DAP12900', 'DAP13000')
		) S
--WHERE	ROWNUM BETWEEN 1 AND 29040

;


SELECT *
FROM O_ITEM_NEW
WHERE 1 = 1
AND	SALES_CD3 IS NOT NULL
--AND SALES_CD3 IN ('DAP11400', 'DAP11500', 'DAP11600', 'DAP11700', 'DAP12400', 'DAP12500', 'DAP12800', 'DAP12900', 'DAP13000')
;






/* eorder.o_qmsorder.cnt */
SELECT
		COUNT(*)
FROM	qms_salesorder SO
		LEFT JOIN O_ITEM_NEW OIN
		ON OIN.ITEM_CD = SO.ITEM_CD /*2024-09-30 hsg LINE_TY에 'Y'값이 없어 죠회가 되지 않아. LEFT JOIN 시 조건을 걸었음 */
		and OIN.LINE_TY = 'Y'
WHERE	1 = 1
	/*2024-09-30 hsg LINE_TY에 'Y'값이 없어 죠회가 되지 않아. LEFT JOIN 시로 취치를 옮김 */
	/* AND OIN.LINE_TY = 'Y' */
	AND NOT(SO.STATUS1 = '980')
	AND SO.STATUS2 >= '620'
	AND OIN.SALES_CD3 IN ('DAP11400', 'DAP11500', 'DAP11600', 'DAP11700', 'DAP12400', 'DAP12500', 'DAP12800', 'DAP12900', 'DAP13000')
	AND SO.ACTUAL_SHIP_DT >= '20240101'
	AND SO.ACTUAL_SHIP_DT <= '20240331'

;





/* eorder.o_qmsorder.list */
SELECT
		/*+ HASH(table) */
		*
FROM	(
			SELECT
				ROW_NUMBER() OVER( ORDER BY XX.ORDERNO DESC, XX.LINE_NO ASC ) AS ROWNUM ,
				XX.* ,
				CASE
					WHEN PRE1 = 'Y' AND PRE2 = 'Y' /* 사전입력 완료 */ THEN '사전'
					WHEN PRE1 = 'Y' AND PRE2 = 'N' /* 사전입력중 */ THEN '사전'
					ELSE '사후' /* 사후입력 대상 */
				END AS QMS_STEP
			FROM	(
						SELECT
								dbo.Sf_getpreorderyn(SO.cust_po) AS PRE1 , dbo.Sf_getpreqtyyn(SO.cust_po) AS PRE2 ,
								ORDERNO, LINE_NO , dbo.SF_GETQMSID(ORDERNO, LINE_NO)AS QMS_ARR , dbo.SF_GETQMSID(ORDERNO, LINE_NO)AS QMS_ARR_TXT ,
								CASE
									WHEN (CONVERT(DECIMAL, dbo.SF_GETPREQTY(SO.cust_po)) >= CONVERT(DECIMAL, SO.ORDER_QTY)
											AND dbo.Sf_getpreorderyn(SO.cust_po) = 'Y'
											AND dbo.Sf_getpreqtyyn(SO.cust_po) = 'Y') THEN CONVERT(DECIMAL, SO.ORDER_QTY)
									WHEN dbo.Sf_getpreorderyn(SO.cust_po) = 'Y' THEN CONVERT(DECIMAL, dbo.SF_GETPREQTY(SO.cust_po))
									ELSE CONVERT(DECIMAL, dbo.Sf_getqmsqty(orderno, line_no))
								END AS QMS_ARR_QTY ,
								CASE
									WHEN ORDER_QTY = dbo.SF_GETQMSQTY(ORDERNO, LINE_NO) THEN '완료'
									ELSE '미완료'
								END AS QMS_STATUS ,
								dbo.SF_GETQMSSHIPTO(ORDERNO, LINE_NO)AS QMS_ARR_SHIPTO , dbo.SF_GETMAILYN(ORDERNO, LINE_NO) AS MAIL_YN ,
								dbo.SF_GETFILEYN(ORDERNO, LINE_NO) AS FILE_YN ,
								SO.ITEM_CD , ORDERTY , CUST_PO , CUST_CD , CUST_NM ,
								dbo.SF_GETQMSQUARTER(ACTUAL_SHIP_DT) AS ACTUAL_SHIP_QUARTER ,
								dbo.SF_GETQMSACTIVEYN(dbo.SF_GETQMSQUARTER(ACTUAL_SHIP_DT)) AS ACTIVEYN ,
								CONCAT(CONCAT(CONCAT(CONCAT(SUBSTRING(ORDER_DT, 0, 4), '-'), SUBSTRING(ORDER_DT, 5, 2)), '-'), SUBSTRING(ORDER_DT, 7, 2)) AS ORDER_DT ,
								CONCAT(CONCAT(CONCAT(CONCAT(SUBSTRING(ACTUAL_SHIP_DT, 0, 4), '-'), SUBSTRING(ACTUAL_SHIP_DT, 5, 2)), '-'), SUBSTRING(ACTUAL_SHIP_DT, 7, 2)) AS ACTUAL_SHIP_DT ,
								SHIPTO_CD, SHIPTO_NM, RTRIM(CONCAT(ADD1, ADD2)) AS ADDR, ITEM_DESC, LOTN, ORDER_QTY, UNIT, SALESREP_NM
								FROM	qms_salesorder SO
										LEFT JOIN O_ITEM_NEW OIN
												ON OIN.ITEM_CD = SO.ITEM_CD /*2024-09-30 hsg LINE_TY에 'Y'값이 없어 죠회가 되지 않아. LEFT JOIN 시 조건을 걸었음 */
												AND OIN.LINE_TY = 'Y'
								WHERE	1 = 1
								/*2024-09-30 hsg LINE_TY에 'Y'값이 없어 죠회가 되지 않아. LEFT JOIN 시로 취치를 옮김 */
								/* AND OIN.LINE_TY = 'Y' */
								AND NOT(SO.STATUS1 = '980')
								AND SO.STATUS2 >= '620'
								AND OIN.SALES_CD3 IN ('DAP11400', 'DAP11500', 'DAP11600', 'DAP11700', 'DAP12400', 'DAP12500', 'DAP12800', 'DAP12900', 'DAP13000')
								AND SO.ACTUAL_SHIP_DT >= '20240101'
								AND SO.ACTUAL_SHIP_DT <= '20240331'
					) XX
		) S
WHERE ROWNUM BETWEEN 1 AND 15

;









SELECT
		*
FROM	(
			SELECT
					ROW_NUMBER() OVER( ORDER BY ITEM_CD ASC ) AS ROWNUM ,
					XX.*
			FROM	(
						SELECT
								IT.ITEM_CD, IT.DESC1, IT.DESC2,
								(
									CASE
										WHEN IT.LINE_TY IS NULL THEN 'N'
										ELSE IT.LINE_TY
									END
								) AS LINE_TY,
								IT.SALES_CD1_NM, IT.SALES_CD2_NM, IT.SALES_CD3_NM, IT.UNIT4
						FROM	O_ITEM_NEW IT
								LEFT JOIN ITEMINFO ITI
										ON IT.ITEM_CD = ITI.ITI_ITEMCD
								LEFT JOIN ITEMBOOKMARK ITB
										ON IT.ITEM_CD = ITB.ITB_ITEMCD AND ITB.ITB_USERID = 'admin'
						WHERE	ITEM_CD NOT IN ('65440', '63111', '254636', '177306')/*('W1', 'R1', 'P1', 'F3', 'F2', 'F1')*/
					) XX
		) S
WHERE	ROWNUM BETWEEN 1 AND 15

;






























