

/* *********** eorder.o_salesorder.getReportFor1121 *********** */
;



SELECT
		SUB.*
FROM	(
			SELECT
					GRP.ITEM_DESC
					, CASE GROUPING(GRP.ACTUAL_SHIP_DT) WHEN 1 THEN '소계' ELSE ACTUAL_SHIP_DT END AS ACTUAL_SHIP_DT
					, SUM(GRP.ORDER_QTY) AS SUM_ORDER_QTY
					, GRP.UNIT
					, GRP.ITEM_CD_3
					, GRP.ADD1
			FROM	(
						SELECT
								SO.ACTUAL_SHIP_DT
								, SO.ITEM_DESC
								, SO.ADD1
								, SO.UNIT
								, SUM(SO.ORDER_QTY) AS ORDER_QTY
								, SUBSTRING(ITEM_CD, 1, 3) AS ITEM_CD_3
						FROM	O_SALESORDER SO
						WHERE	ACTUAL_SHIP_DT >= '20230207'
						AND		ACTUAL_SHIP_DT <= '20230228'
						AND		CUST_CD = '1795'
						AND		SHIPTO_NM = TRIM('인천 인스파이어-(주)하나공간')
						AND		ITEM_DESC IN ( TRIM('방화 15*900*1800 테파드'), TRIM('방화 15*900*1800 평보드'), TRIM('방화방수 15*900*1800 평보드') )
						GROUP BY ITEM_DESC , ACTUAL_SHIP_DT , UNIT , ADD1 , SUBSTRING(ITEM_CD, 1, 3)
					) GRP
			GROUP BY GRP.ITEM_DESC , GRP.ACTUAL_SHIP_DT , GRP.UNIT , GRP.ITEM_CD_3 , GRP.ADD1 WITH ROLLUP
			HAVING GROUPING(GRP.ITEM_DESC) = 0
	)	SUB
ORDER BY SUB.ITEM_DESC ASC , SUB.ACTUAL_SHIP_DT ASC
;



						SELECT
								SO.ACTUAL_SHIP_DT
								, SO.ITEM_DESC
								, SO.ADD1
								, SO.UNIT
								, SUM(SO.ORDER_QTY) AS ORDER_QTY
								, SUBSTRING(ITEM_CD, 1, 3) AS ITEM_CD_3
								, max(SHIPTO_NM) AS aaaa
						FROM	O_SALESORDER SO
						WHERE	ACTUAL_SHIP_DT >= '20230207'
						AND		ACTUAL_SHIP_DT <= '20230228'
						AND		CUST_CD = '1795'
						AND		SHIPTO_NM = TRIM('인천 인스파이어-(주)하나공간')
						AND		ITEM_DESC IN ( TRIM('방화 15*900*1800 테파드'), TRIM('방화 15*900*1800 평보드'), TRIM('방화방수 15*900*1800 평보드') )
						GROUP BY ITEM_DESC , ACTUAL_SHIP_DT , UNIT , ADD1 , SUBSTRING(ITEM_CD, 1, 3)
;


SELECT
		ITEM_DESC , ACTUAL_SHIP_DT , UNIT , ADD1
FROM	O_SALESORDER A
WHERE	1 = 1
AND		ACTUAL_SHIP_DT >= '20230207'
AND		ACTUAL_SHIP_DT >= '20230228'
AND		CUST_CD = '1795'
AND		SHIPTO_NM = TRIM('인천 인스파이어-(주)하나공간')
AND		ITEM_DESC IN ( TRIM('방화 15*900*1800 테파드'), TRIM('방화 15*900*1800 평보드'), TRIM('방화방수 15*900*1800 평보드') )
GROUP BY ITEM_DESC , ACTUAL_SHIP_DT , UNIT , ADD1 , SUBSTRING(ITEM_CD, 1, 3)
--ORDER BY
;


			SELECT
					GRP.ITEM_DESC
					, CASE GROUPING(GRP.ACTUAL_SHIP_DT) WHEN 1 THEN '소계' ELSE ACTUAL_SHIP_DT END AS ACTUAL_SHIP_DT
					, GROUPING(GRP.ITEM_DESC) AS aaa
					, GROUPING(GRP.ACTUAL_SHIP_DT) AS bbb
					, GROUPING(GRP.UNIT) AS ccc
					, GROUPING(GRP.ITEM_CD_3) AS ddd
					, GROUPING(GRP.ADD1) AS ddd
					, SUM(GRP.ORDER_QTY) AS SUM_ORDER_QTY
					, GRP.UNIT
					, GRP.ITEM_CD_3
					, GRP.ADD1
			FROM	(
						SELECT
								SO.ACTUAL_SHIP_DT
								, SO.ITEM_DESC
								, SO.ADD1
								, SO.UNIT
								, SUM(SO.ORDER_QTY) AS ORDER_QTY
								, SUBSTRING(ITEM_CD, 1, 3) AS ITEM_CD_3
						FROM	O_SALESORDER SO
						WHERE	ACTUAL_SHIP_DT >= '20230207'
						AND		ACTUAL_SHIP_DT <= '20230228'
						AND		CUST_CD = '1795'
						AND		SHIPTO_NM = TRIM('인천 인스파이어-(주)하나공간')
						AND		ITEM_DESC IN ( TRIM('방화 15*900*1800 테파드'), TRIM('방화 15*900*1800 평보드'), TRIM('방화방수 15*900*1800 평보드') )
						GROUP BY ITEM_DESC , ACTUAL_SHIP_DT , UNIT , ADD1 , SUBSTRING(ITEM_CD, 1, 3)
					) GRP
			GROUP BY GRP.ITEM_DESC , GRP.ACTUAL_SHIP_DT , GRP.UNIT , GRP.ITEM_CD_3 , GRP.ADD1
			WITH ROLLUP
			HAVING GROUPING(GRP.ITEM_DESC) = 0
;





SELECT
		SUB.*
FROM	(
			SELECT
					GRP.ITEM_DESC
					, CASE GROUPING(GRP.ACTUAL_SHIP_DT) WHEN 1 THEN '소계' ELSE ACTUAL_SHIP_DT END AS ACTUAL_SHIP_DT
					, SUM(GRP.ORDER_QTY) AS SUM_ORDER_QTY
					, GRP.UNIT
					, GRP.ITEM_CD_3
					, GRP.ADD1
			FROM	(
						SELECT
								SO.ACTUAL_SHIP_DT
								, SO.ITEM_DESC
								, SO.ADD1
								, SO.UNIT
								, SUM(SO.ORDER_QTY) AS ORDER_QTY
								, SUBSTRING(ITEM_CD, 1, 3) AS ITEM_CD_3
						FROM	O_SALESORDER SO
						WHERE	ACTUAL_SHIP_DT >= '20230207'
						AND		ACTUAL_SHIP_DT <= '20230228'
						AND		CUST_CD = '1795'
						AND		SHIPTO_NM = TRIM('인천 인스파이어-(주)하나공간')
						AND		ITEM_DESC IN ( TRIM('방화 15*900*1800 테파드'), TRIM('방화 15*900*1800 평보드'), TRIM('방화방수 15*900*1800 평보드') )
						GROUP BY ITEM_DESC , ACTUAL_SHIP_DT , UNIT , ADD1 , SUBSTRING(ITEM_CD, 1, 3)
					) GRP
			GROUP BY GRP.ITEM_DESC , GRP.ACTUAL_SHIP_DT , GRP.UNIT , GRP.ITEM_CD_3 , GRP.ADD1 WITH ROLLUP
			HAVING GROUPING(GRP.ITEM_DESC) = 0
	)	SUB
WHERE	1 = 1
AND		( SUB.ACTUAL_SHIP_DT = '소계' OR SUB.ADD1 IS NOT NULL )
ORDER BY SUB.ITEM_DESC ASC , SUB.ACTUAL_SHIP_DT ASC
;





/* *********** eorder.o_salesorder.getReportPeriodDate *********** */
;

SELECT
		MIN(ACTUAL_SHIP_DT) AS START_DATE , MAX(ACTUAL_SHIP_DT) AS END_DATE
FROM	O_SALESORDER SO
WHERE	1 = 1
AND		ACTUAL_SHIP_DT >= '20230207'
AND		ACTUAL_SHIP_DT >= '20230228'
AND		CUST_CD = '1795'
AND		SHIPTO_NM = TRIM('인천 인스파이어-(주)하나공간')
AND		ITEM_DESC IN ( TRIM('방화 15*900*1800 테파드'), TRIM('방화 15*900*1800 평보드'), TRIM('방화방수 15*900*1800 평보드') )
;





/* *********** eorder.o_salesorder.getCustInfoForReport *********** */
;

SELECT
		CUST_NM , SALESREP_NM , TRIM('인천 인스파이어-(주)하나공간') AS SHIPTO_NM
FROM	O_CUSTOMER
WHERE	CUST_CD = '1795'
;






























