
/* ***************************************************************************************************************************************** */
/* *********** 로그인 체크 *********** */


SELECT
		TOP 1 *
FROM	USERPSWDHISTORY
WHERE	UPH_ID = '10177560'
ORDER BY UPH_INDATE DESC
;


SELECT
		*
FROM	CONFIG
WHERE	CF_ID = 'USERPSWDLOCK'
;

SELECT
		COUNT(*) FAIL_CNT,
		MAX(LL_INDATE) LAST_LOGIN_DATE
FROM	LOGINLOG
WHERE	LL_SEQ > ISNULL((
							SELECT
									MAX(LL_SEQ)
							FROM	LOGINLOG
							WHERE	LL_USERID = '10177560'
							AND		LL_PSYN = 'Y'
						), 0)
AND		LL_USERID = '10177560'
AND		LL_PSYN = 'N'
AND		LL_INDATE >= CONVERT(DATETIME, '2023-06-19 10:19:41') 
;

SELECT
		US.*,
		ST.*,
		CU.CUST_NM,
		ISNULL((
					SELECT
							USER_NM
					FROM	O_USER
					WHERE	USERID = CU.SALESREP_CD
				), '') SALES_NM
FROM	O_USER US
		LEFT JOIN O_SHIPTO ST
				ON ST.CUST_CD = US.CUST_CD AND ST.SHIPTO_CD = US.USER_SHIPTOCD
		LEFT JOIN O_CUSTOMER CU
				ON CU.CUST_CD = US.CUST_CD
WHERE	USERID NOT IN ('9', '1', '2', '3', '4', '5')
AND		USERID = '10177560'
AND		USER_PWD = dbo.UDF_SETPASSWORD('P@ssw0rd') 
;

SELECT
		MAX(LL.LL_SEQ)+ 1
FROM	LOGINLOG LL;


--INSERT INTO LOGINLOG ( LL_SEQ, LL_USERID, LL_TYPE, LL_PSYN, LL_INDATE ) VALUES ( ? , ? , ? , ? , GETDATE() ) 

-- 468154(Long), 10177560(String), F(String), Y(String)
;


SELECT
		COUNT(*)
FROM	LOGINLOG
WHERE	LL_USERID = '10177560'
AND		LL_PSYN = 'Y'
;

SELECT
		*
FROM	CONFIG
WHERE	CF_ID = 'BROWSERTITLE'
;



SELECT
		*
FROM	(
			SELECT
					ROW_NUMBER() OVER( ORDER BY ( SELECT 1) ) AS ROWNUM , XX.*
			FROM	( SELECT * FROM	CONFIG ) XX
		) S 
;

SELECT
		COUNT(*)
FROM	O_CUST_ORDER_H COH
		LEFT JOIN O_CUSTOMER CU ON COH.CUST_CD = CU.CUST_CD
		LEFT JOIN O_SHIPTO ST ON COH.SHIPTO_CD = ST.SHIPTO_CD
		LEFT JOIN O_USER US_SALES ON CU.SALESREP_CD = US_SALES.USERID
WHERE	RTRIM(COH.USERID) = RTRIM('10177560')
AND		COH.INDATE >= CONVERT(DATE, '2024-11-07')
AND		COH.INDATE <= CONVERT(DATE, '2024-11-07')
AND		COH.STATUS_CD IN ('99') 
;

SELECT
		CU.*,
		US.USER_NM,
		US.AUTHORITY,
		US.USER_FILE,
		US.CELL_NO,
		US.USER_POSITION ,
		(
			SELECT
					COUNT(*)
			FROM	O_USER
			WHERE	CUST_CD = CU.CUST_CD
			AND		AUTHORITY = 'CO'
		) AS CUSTOMER_USER_CNT ,
		(
			SELECT
					COUNT(*)
			FROM	O_USER
			WHERE	CUST_CD = CU.CUST_CD
			AND		AUTHORITY = 'CT'
		) AS SHIPTO_USER_CNT ,
		(
			SELECT
					COUNT(*)
			FROM	O_SHIPTO
			WHERE	CUST_CD = CU.CUST_CD
		) AS SHIPTO_CNT ,
		US2.USER_NM AS CSUSER_NM ,
		US2.TEL_NO AS CSUSER_TEL ,
		US2.CELL_NO AS CSUSER_CELL ,
		US2.USER_FILE AS CSUSER_FILE ,
		US2.USER_POSITION AS CSUSER_POSITION
FROM	O_CUSTOMER CU
		LEFT JOIN O_USER US ON CU.SALESREP_CD = US.USERID
		LEFT JOIN O_CSSALESMAP CSM ON CU.SALESREP_CD = CSM.SALESUSERID AND CSM.FIXEDYN = 'Y'
		LEFT JOIN O_USER US2 ON CSM.CSUSERID = US2.USERID
WHERE	CU.CUST_CD = '10177560'
;


