SELECT
		*
FROM	(
			SELECT
					ROW_NUMBER() OVER( ORDER BY XX.INDATE DESC ) AS ROWNUM ,
					XX.*
			FROM	(
						SELECT
								COH.* ,
								( SELECT USER_NM FROM O_USER WHERE RTRIM(USERID) = RTRIM(COH.USERID)) AS USER_NM ,
								CU.CUST_NM , ST.SHIPTO_NM , US_SALES.USERID AS SALESUSERID, US_SALES.USER_NM AS SALESUSER_NM ,
								( SELECT CSUSERID FROM O_CSSALESMAP WHERE SALESUSERID = US_SALES.USERID AND FIXEDYN = 'Y') AS CSUSERID ,
								( SELECT SUB1.USER_NM FROM O_USER SUB1, O_CSSALESMAP SUB2 WHERE SUB1.USERID = SUB2.CSUSERID AND SUB2.SALESUSERID = US_SALES.USERID AND SUB2.FIXEDYN = 'Y') AS CSUSER_NM ,
								( SELECT COUNT(*) FROM O_CUST_ORDER_D WHERE REQ_NO = COH.REQ_NO) AS ITEM_CNT ,
								( SELECT TOP 1 CONFIRM_DT FROM O_ORDER_CONFIRM_H WHERE REQ_NO = COH.REQ_NO) AS CONFIRM_DT2 ,
								QM.QMS_TEMP_ID
						FROM	O_CUST_ORDER_H COH
								LEFT OUTER JOIN QMS_PRE_MAST QM
										ON QM.REQ_NO = COH.REQ_NO AND QM.DELETEYN = 'N'
								LEFT JOIN O_CUSTOMER CU
										ON COH.CUST_CD = CU.CUST_CD
								LEFT JOIN O_SHIPTO ST
										ON COH.SHIPTO_CD = ST.SHIPTO_CD
								LEFT JOIN O_USER US_SALES
										ON CU.SALESREP_CD = US_SALES.USERID
						WHERE	COH.INDATE >= CONVERT(DATE, '2024-10-18') AND COH.INDATE < DATEADD(day, 1, CONVERT(DATE, '2024-10-18'))
						AND		COH.STATUS_CD IN ('00')
					) XX
		) S
WHERE	ROWNUM BETWEEN 1 AND 10
;




SELECT
		*
FROM	(
			SELECT
					ROW_NUMBER() OVER( ORDER BY XX.INDATE DESC ) AS ROWNUM ,
					XX.*
			FROM	(
						SELECT
								COH.* ,
								( SELECT USER_NM FROM O_USER WHERE RTRIM(USERID) = RTRIM(COH.USERID) ) AS USER_NM ,
								CU.CUST_NM , ST.SHIPTO_NM , US_SALES.USERID AS SALESUSERID, US_SALES.USER_NM AS SALESUSER_NM ,
								(SELECT CSUSERID FROM O_CSSALESMAP WHERE SALESUSERID = US_SALES.USERID AND FIXEDYN = 'Y') AS CSUSERID ,
								(SELECT SUB1.USER_NM FROM O_USER SUB1, O_CSSALESMAP SUB2 WHERE SUB1.USERID = SUB2.CSUSERID AND SUB2.SALESUSERID = US_SALES.USERID AND SUB2.FIXEDYN = 'Y') AS CSUSER_NM ,
								(SELECT COUNT(*) FROM O_CUST_ORDER_D WHERE REQ_NO = COH.REQ_NO) AS ITEM_CNT ,
								( SELECT TOP 1 CONFIRM_DT FROM O_ORDER_CONFIRM_H WHERE REQ_NO = COH.REQ_NO) AS CONFIRM_DT2 ,
								QM.QMS_TEMP_ID
						FROM	O_CUST_ORDER_H COH
								LEFT OUTER JOIN QMS_PRE_MAST QM
										ON QM.REQ_NO = COH.REQ_NO
										AND QM.DELETEYN = 'N'
								LEFT JOIN O_CUSTOMER CU
										ON COH.CUST_CD = CU.CUST_CD
								LEFT JOIN O_SHIPTO ST
										ON COH.SHIPTO_CD = ST.SHIPTO_CD
								LEFT JOIN O_USER US_SALES
										ON CU.SALESREP_CD = US_SALES.USERID
								WHERE	COH.INDATE >= CONVERT(DATE, '2024-10-18')
								AND COH.INDATE < DATEADD(day, 1, CONVERT(DATE, '2024-10-18'))
					) XX
		) S
	WHERE	ROWNUM BETWEEN 1 AND 10

;



SELECT dbo.SF_GETQMSID_SEQ(3) AS NEW_QMS_ID;


-- INSERT INTO QMS_ORD_FRCN	(QMS_ID, QMS_SEQ, QMS_FRCN_ID, KEYCODE, CREATEUSER, CREATETIME, UPDATEUSER, UPDATETIME, DELETEYN)
SELECT
		'20241Q0099', 1, QMS_FRCN_ID, KEYCODE, CREATEUSER, CREATETIME, UPDATEUSER, UPDATETIME, DELETEYN
FROM	QMS_ORD_FRCN QOF
WHERE	EXISTS	(
					SELECT	*
					FROM	QMS_ORD_MAST A , QMS_ORD_DETL B , QMS_SALESORDER C
					WHERE	A.QMS_ID = B.QMS_ID
					AND		A.QMS_SEQ = B.QMS_SEQ
					AND		QOF.QMS_ID = A.QMS_ID
					AND		QOF.QMS_SEQ = A.QMS_SEQ
					AND		A.DELETEYN = 'N'
					AND		B.DELETEYN = 'N'
					AND		B.ORDERNO = C.ORDERNO
					AND		B.LINE_NO = C.LINE_NO
					AND		A.CUST_CD = '10172642'
					AND		C.SHIPTO_CD = '0010172642'
				)
;


SELECT * FROM QMS_ORD_FRCN;






					SELECT	A.CUST_CD, C.SHIPTO_CD
					FROM	QMS_ORD_MAST A , QMS_ORD_DETL B , QMS_SALESORDER C
					WHERE	A.QMS_ID = B.QMS_ID
					AND		A.QMS_SEQ = B.QMS_SEQ
					AND		A.DELETEYN = 'N'
					AND		B.DELETEYN = 'N'
					AND		B.ORDERNO = C.ORDERNO
					AND		B.LINE_NO = C.LINE_NO
--					AND		A.CUST_CD = '10172665'
--					AND		C.SHIPTO_CD = '9005263181'
					AND 	EXISTS	(
										SELECT * FROM QMS_ORD_FRCN T WHERE A.QMS_ID = T.QMS_ID AND A.QMS_SEQ = T.QMS_SEQ
									)
					GROUP BY A.CUST_CD, C.SHIPTO_CD



--WHERE	(QMS_ID, QMS_SEQ) IN (
--								SELECT
--										QMS_ID, QMS_SEQ
--								FROM	(
--											SELECT
--													RANK() OVER(PARTITION BY A.CUST_CD, C.SHIPTO_CD ORDER BY A.QMS_ID DESC, A.QMS_SEQ DESC, B.QMS_DETL_ID DESC) AS RNUM ,
--													A.*
--											FROM	QMS_ORD_MAST A , QMS_ORD_DETL B , QMS_SALESORDER C
--											WHERE	A.QMS_ID = B.QMS_ID
--											AND		A.QMS_SEQ = B.QMS_SEQ
--											AND		A.DELETEYN = 'N'
--											AND		B.DELETEYN = 'N'
--											AND		B.ORDERNO = C.ORDERNO
--											AND		B.LINE_NO = C.LINE_NO
--											AND		A.CUST_CD = ?
--											AND		C.SHIPTO_CD = ?
--										)
--								WHERE	RNUM = 1
--							)

;
--20241Q0099(String), 1(String), 10172665(String), 9005263181(String), 부산 북항 초고층복합개발사업-롯데(String), admin(String), admin(String), T(String)








SELECT
	COUNT(*)
FROM
	O_SALESORDER SO
WHERE
	SO.STATUS2 IN (560, 580, 620)
	AND ((SO.STATUS1 = 580
		AND SO.STATUS2 = 620)
--		AND SO.REQUEST_DT < TO_CHAR(SYSDATE, 'yyyymmdd'))
		AND SO.REQUEST_DT < FORMAT(getDate(), 'yyyymmdd'))
	AND SO.ORDERTY <> 'KL'
	AND SO.ORDER_DT >= ?
	AND SO.ORDER_DT <= ?

;






/* eorder.o_qmsorder.list */
SELECT
		/*+ HASH(table) */
		*
FROM	(
			SELECT
					ROW_NUMBER() OVER( ORDER BY XX.ORDERNO DESC, XX.LINE_NO ASC ) AS ROWNUM ,
					XX.* ,
					CASE
						WHEN PRE1 = 'Y' AND PRE2 = 'Y' /* 사전입력 완료 */ THEN '사전'
						WHEN PRE1 = 'Y' AND PRE2 = 'N' /* 사전입력중 */ THEN '사전'
						ELSE '사후' /* 사후입력 대상 */
					END AS QMS_STEP
			FROM	(
						SELECT
								dbo.Sf_getpreorderyn(SO.cust_po) AS PRE1 ,
								dbo.Sf_getpreqtyyn(SO.cust_po) AS PRE2 ,
								ORDERNO, LINE_NO ,
								dbo.SF_GETQMSID(ORDERNO, LINE_NO)AS QMS_ARR ,
								dbo.SF_GETQMSID(ORDERNO, LINE_NO)AS QMS_ARR_TXT ,
								CASE
									WHEN (CONVERT(DECIMAL, dbo.SF_GETPREQTY(SO.cust_po)) >= CONVERT(DECIMAL, SO.ORDER_QTY)
											AND dbo.Sf_getpreorderyn(SO.cust_po) = 'Y'
											AND dbo.Sf_getpreqtyyn(SO.cust_po) = 'Y')
										THEN CONVERT(DECIMAL, SO.ORDER_QTY)
									WHEN dbo.Sf_getpreorderyn(SO.cust_po) = 'Y' THEN CONVERT(DECIMAL, dbo.SF_GETPREQTY(SO.cust_po))
									ELSE CONVERT(DECIMAL, dbo.Sf_getqmsqty(orderno, line_no))
								END AS QMS_ARR_QTY ,
								CASE WHEN ORDER_QTY = dbo.SF_GETQMSQTY(ORDERNO, LINE_NO) THEN '완료' ELSE '미완료' END AS QMS_STATUS ,
								dbo.SF_GETQMSSHIPTO(ORDERNO, LINE_NO)AS QMS_ARR_SHIPTO ,
								dbo.SF_GETMAILYN(ORDERNO, LINE_NO) AS MAIL_YN ,
								dbo.SF_GETFILEYN(ORDERNO, LINE_NO) AS FILE_YN ,
								SO.ITEM_CD , ORDERTY , CUST_PO , CUST_CD , CUST_NM , dbo.SF_GETQMSQUARTER(ACTUAL_SHIP_DT) AS ACTUAL_SHIP_QUARTER ,
								dbo.SF_GETQMSACTIVEYN(dbo.SF_GETQMSQUARTER(ACTUAL_SHIP_DT)) AS ACTIVEYN ,
								CONCAT(CONCAT(CONCAT(CONCAT(SUBSTRING(ORDER_DT, 0, 4), '-'), SUBSTRING(ORDER_DT, 5, 2)), '-'), SUBSTRING(ORDER_DT, 7, 2)) AS ORDER_DT ,
								CONCAT(CONCAT(CONCAT(CONCAT(SUBSTRING(ACTUAL_SHIP_DT, 0, 4), '-'), SUBSTRING(ACTUAL_SHIP_DT, 5, 2)), '-'), SUBSTRING(ACTUAL_SHIP_DT, 7, 2)) AS ACTUAL_SHIP_DT ,
								SHIPTO_CD, SHIPTO_NM, RTRIM(CONCAT(ADD1, ADD2)) AS ADDR, ITEM_DESC, LOTN, ORDER_QTY, UNIT, SALESREP_NM,
								OIN.SALES_CD3
						FROM	qms_salesorder SO
								LEFT JOIN O_ITEM_NEW OIN
										ON OIN.ITEM_CD = SO.ITEM_CD /*2024-09-30 hsg LINE_TY에 'Y'값이 없어 죠회가 되지 않아. LEFT JOIN 시 조건을 걸었음 */
										AND OIN.LINE_TY = 'Y'
--										AND	OIN.SALES_CD3 IN ('DAP11400', 'DAP11500', 'DAP11600', 'DAP11700', 'DAP12400', 'DAP12500', 'DAP12800', 'DAP12900', 'DAP13000')
						WHERE
								/*2024-09-30 hsg LINE_TY에 'Y'값이 없어 죠회가 되지 않아. LEFT JOIN 시로 취치를 옮김 */
								/* AND OIN.LINE_TY = 'Y' */
								1 = 1
						AND		NOT(SO.STATUS1 = '980')
						AND		SO.STATUS2 >= '620'
						AND		SO.ACTUAL_SHIP_DT >= '20240401'
						AND		SO.ACTUAL_SHIP_DT <= '20240630'
--						AND		OIN.SALES_CD3 IN ('DAP11400', 'DAP11500', 'DAP11600', 'DAP11700', 'DAP12400', 'DAP12500', 'DAP12800', 'DAP12900', 'DAP13000')
					) XX
			WHERE	1 = 1
--			AND 	XX.SALES_CD3 IS NOT NULL
			AND		XX.SALES_CD3 IN ('DAP11400', 'DAP11500', 'DAP11600', 'DAP11700', 'DAP12400', 'DAP12500', 'DAP12800', 'DAP12900', 'DAP13000')
		) S
--WHERE	ROWNUM BETWEEN 1 AND 29040

;


SELECT *
FROM O_ITEM_NEW
WHERE 1 = 1
AND	SALES_CD3 IS NOT NULL
--AND SALES_CD3 IN ('DAP11400', 'DAP11500', 'DAP11600', 'DAP11700', 'DAP12400', 'DAP12500', 'DAP12800', 'DAP12900', 'DAP13000')
;






/* eorder.o_qmsorder.cnt */
SELECT
		COUNT(*)
FROM	qms_salesorder SO
		LEFT JOIN O_ITEM_NEW OIN
		ON OIN.ITEM_CD = SO.ITEM_CD /*2024-09-30 hsg LINE_TY에 'Y'값이 없어 죠회가 되지 않아. LEFT JOIN 시 조건을 걸었음 */
		and OIN.LINE_TY = 'Y'
WHERE	1 = 1
	/*2024-09-30 hsg LINE_TY에 'Y'값이 없어 죠회가 되지 않아. LEFT JOIN 시로 취치를 옮김 */
	/* AND OIN.LINE_TY = 'Y' */
	AND NOT(SO.STATUS1 = '980')
	AND SO.STATUS2 >= '620'
	AND OIN.SALES_CD3 IN ('DAP11400', 'DAP11500', 'DAP11600', 'DAP11700', 'DAP12400', 'DAP12500', 'DAP12800', 'DAP12900', 'DAP13000')
	AND SO.ACTUAL_SHIP_DT >= '20240101'
	AND SO.ACTUAL_SHIP_DT <= '20240331'

;





/* eorder.o_qmsorder.list */
SELECT
		/*+ HASH(table) */
		*
FROM	(
			SELECT
				ROW_NUMBER() OVER( ORDER BY XX.ORDERNO DESC, XX.LINE_NO ASC ) AS ROWNUM ,
				XX.* ,
				CASE
					WHEN PRE1 = 'Y' AND PRE2 = 'Y' /* 사전입력 완료 */ THEN '사전'
					WHEN PRE1 = 'Y' AND PRE2 = 'N' /* 사전입력중 */ THEN '사전'
					ELSE '사후' /* 사후입력 대상 */
				END AS QMS_STEP
			FROM	(
						SELECT
								dbo.Sf_getpreorderyn(SO.cust_po) AS PRE1 , dbo.Sf_getpreqtyyn(SO.cust_po) AS PRE2 ,
								ORDERNO, LINE_NO , dbo.SF_GETQMSID(ORDERNO, LINE_NO)AS QMS_ARR , dbo.SF_GETQMSID(ORDERNO, LINE_NO)AS QMS_ARR_TXT ,
								CASE
									WHEN (CONVERT(DECIMAL, dbo.SF_GETPREQTY(SO.cust_po)) >= CONVERT(DECIMAL, SO.ORDER_QTY)
											AND dbo.Sf_getpreorderyn(SO.cust_po) = 'Y'
											AND dbo.Sf_getpreqtyyn(SO.cust_po) = 'Y') THEN CONVERT(DECIMAL, SO.ORDER_QTY)
									WHEN dbo.Sf_getpreorderyn(SO.cust_po) = 'Y' THEN CONVERT(DECIMAL, dbo.SF_GETPREQTY(SO.cust_po))
									ELSE CONVERT(DECIMAL, dbo.Sf_getqmsqty(orderno, line_no))
								END AS QMS_ARR_QTY ,
								CASE
									WHEN ORDER_QTY = dbo.SF_GETQMSQTY(ORDERNO, LINE_NO) THEN '완료'
									ELSE '미완료'
								END AS QMS_STATUS ,
								dbo.SF_GETQMSSHIPTO(ORDERNO, LINE_NO)AS QMS_ARR_SHIPTO , dbo.SF_GETMAILYN(ORDERNO, LINE_NO) AS MAIL_YN ,
								dbo.SF_GETFILEYN(ORDERNO, LINE_NO) AS FILE_YN ,
								SO.ITEM_CD , ORDERTY , CUST_PO , CUST_CD , CUST_NM ,
								dbo.SF_GETQMSQUARTER(ACTUAL_SHIP_DT) AS ACTUAL_SHIP_QUARTER ,
								dbo.SF_GETQMSACTIVEYN(dbo.SF_GETQMSQUARTER(ACTUAL_SHIP_DT)) AS ACTIVEYN ,
								CONCAT(CONCAT(CONCAT(CONCAT(SUBSTRING(ORDER_DT, 0, 4), '-'), SUBSTRING(ORDER_DT, 5, 2)), '-'), SUBSTRING(ORDER_DT, 7, 2)) AS ORDER_DT ,
								CONCAT(CONCAT(CONCAT(CONCAT(SUBSTRING(ACTUAL_SHIP_DT, 0, 4), '-'), SUBSTRING(ACTUAL_SHIP_DT, 5, 2)), '-'), SUBSTRING(ACTUAL_SHIP_DT, 7, 2)) AS ACTUAL_SHIP_DT ,
								SHIPTO_CD, SHIPTO_NM, RTRIM(CONCAT(ADD1, ADD2)) AS ADDR, ITEM_DESC, LOTN, ORDER_QTY, UNIT, SALESREP_NM
								FROM	qms_salesorder SO
										LEFT JOIN O_ITEM_NEW OIN
												ON OIN.ITEM_CD = SO.ITEM_CD /*2024-09-30 hsg LINE_TY에 'Y'값이 없어 죠회가 되지 않아. LEFT JOIN 시 조건을 걸었음 */
												AND OIN.LINE_TY = 'Y'
								WHERE	1 = 1
								/*2024-09-30 hsg LINE_TY에 'Y'값이 없어 죠회가 되지 않아. LEFT JOIN 시로 취치를 옮김 */
								/* AND OIN.LINE_TY = 'Y' */
								AND NOT(SO.STATUS1 = '980')
								AND SO.STATUS2 >= '620'
								AND OIN.SALES_CD3 IN ('DAP11400', 'DAP11500', 'DAP11600', 'DAP11700', 'DAP12400', 'DAP12500', 'DAP12800', 'DAP12900', 'DAP13000')
								AND SO.ACTUAL_SHIP_DT >= '20240101'
								AND SO.ACTUAL_SHIP_DT <= '20240331'
					) XX
		) S
WHERE ROWNUM BETWEEN 1 AND 15

;









SELECT
		*
FROM	(
			SELECT
					ROW_NUMBER() OVER( ORDER BY ITEM_CD ASC ) AS ROWNUM ,
					XX.*
			FROM	(
						SELECT
								IT.ITEM_CD, IT.DESC1, IT.DESC2,
								(
									CASE
										WHEN IT.LINE_TY IS NULL THEN 'N'
										ELSE IT.LINE_TY
									END
								) AS LINE_TY,
								IT.SALES_CD1_NM, IT.SALES_CD2_NM, IT.SALES_CD3_NM, IT.UNIT4
						FROM	O_ITEM_NEW IT
								LEFT JOIN ITEMINFO ITI
										ON IT.ITEM_CD = ITI.ITI_ITEMCD
								LEFT JOIN ITEMBOOKMARK ITB
										ON IT.ITEM_CD = ITB.ITB_ITEMCD AND ITB.ITB_USERID = 'admin'
						WHERE	ITEM_CD NOT IN ('65440', '63111', '254636', '177306')/*('W1', 'R1', 'P1', 'F3', 'F2', 'F1')*/
						AND 	IT.SALES_CD3 IN ('DAP11400', 'DAP11500', 'DAP11600', 'DAP11700', 'DAP12400', 'DAP12500', 'DAP12800', 'DAP12900', 'DAP13000')
					) XX
		) S
WHERE	ROWNUM BETWEEN 1 AND 15

;





SELECT
		*
FROM	(
			SELECT
					ROW_NUMBER() OVER( ORDER BY USER_SORT1 ASC, USER_SORT2 ASC, USER_SORT3 ASC, USER_SORT4 ASC ) AS ROWNUM ,
					XX.*
			FROM	(
						SELECT
								LIST.*
						FROM	(
									SELECT
											US.*, CU.CUST_NM ,
											CASE
												WHEN (US.AUTHORITY = 'SH' OR US.AUTHORITY = 'SM' OR US.AUTHORITY = 'SR') THEN
														(
															SELECT
																	(
																		SELECT
																				USER_NM
																		FROM	O_USER
																		WHERE	USERID = CSM.CSUSERID
																	)
															FROM	O_CSSALESMAP CSM
															WHERE	CSM.SALESUSERID = US.USERID
															AND		CSM.FIXEDYN = 'Y'
														)
												ELSE ''
											END CS_SALESUSER ,
											CASE
												WHEN (US.AUTHORITY = 'SH' OR US.AUTHORITY = 'SM' OR US.AUTHORITY = 'SR') THEN
														(
															SELECT
																	COUNT(*)
															FROM	O_CUSTOMER
															WHERE	SALESREP_CD = US.USERID
														)
												ELSE -1
											END CUSTOMER_CNT
									FROM	O_USER US
											LEFT JOIN O_CUSTOMER CU
													ON CU.CUST_CD = US.CUST_CD
									WHERE	USERID NOT IN ('9', '1', '2', '3', '4', '5', '6')
									AND		US.AUTHORITY = 'AD'
									AND		AUTHORITY NOT IN ('AS','CO','CT')
								) LIST
					) XX
		) S
WHERE	ROWNUM BETWEEN 1 AND 10

;

--AD(String), AS(String), CO(String), CT(String), 1(Integer), 10(Integer)


SELECT	*
FROM	O_USER
WHERE	1 = 1
AND		USERID in ('admin', 'develop')
--AND		USERID = 'develop'

;

SELECT dbo.UDF_SETPASSWORD('ABCDE')


--INSERT INTO O_USER (USERID, USER_PWD, PASSCHANGE_YN, USER_NM, AUTHORITY, TEL_NO, AGREE_YN, INSERT_DT, CUST_CD, DEPT_CD, JDEID, INSERTID, UPDATE_DT, UPDATEID, TEAM_NM, TEAM_CD, CELL_NO, DUMMY, FAIL_CNT, INDATE, MODATE, USER_POSITION, USER_EMAIL, USER_USE, USER_VIEW, USER_DEPTH, USER_PARENT, USER_CATE1, USER_CATE2, USER_CATE3, USER_CATE4, USER_SORT1, USER_SORT2, USER_SORT3, USER_SORT4, USER_FILE, USER_FILETYPE, USER_EORDER, USER_SHIPTOCD, USER_AGREE, USER_APPPUSHKEY, USER_APPPUSHYN1, USER_APPPUSHYN2, USER_APPPUSHYN3)
--SELECT	*
--FROM	O_USER
--WHERE	1 = 1
----AND		USERID in ('admin', 'develop')
--AND		USERID = 'admin'





--UPDATE
--	O_USER US
--SET
--	USER_PWD = dbo.UDF_SETPASSWORD(?),
--	TEL_NO = ?,
--	CELL_NO = ?,
--	UPDATEID = ?,
--	USER_POSITION = ?,
--	USER_EMAIL = ?,
--	UPDATE_DT = SUBSTRING(CONVERT(CHAR(19), GETDATE(), 20), 1, 16),
--	MODATE = GETDATE()
--WHERE
--	USERID = ?

;








SELECT
		*
FROM	(
			SELECT
					ROW_NUMBER() OVER( ORDER BY XX.CUST_PO ASC, XX.LINE_NO ASC ) AS ROWNUM ,
					XX.*
			FROM	(
						SELECT
								OCD.* ,
								OCH.REQ_NO,
								OCH.COMPANY_CD,
								OCH.PICKING_DT,
								OCH.STATUS_CD,
								OCH.CUSTOMMATTER,
								OCH.REQUEST_DT,
								OCH.REQUEST_TIME,
								OCH.REMARK,
								OST.QUOTE_QT ,
								(SELECT PT_NAME FROM PLANT WHERE WERKS = OCH.COMPANY_CD) AS PT_NAME ,
								(SELECT DESC1 FROM O_ITEM_NEW WHERE ITEM_CD = OCD.ITEM_CD) AS ITEM_NAME ,
								(SELECT QUANTITY FROM O_CUST_ORDER_D WHERE REQ_NO = OCH.REQ_NO AND LINE_NO = OCD.LINE_NO) AS COD_QUANTITY ,
								(SELECT CC_NAME FROM COMMONCODE WHERE CC_PARENT = 'C01' AND CC_CODE = OCD.OCD_RETURNCD) AS ITEM_RETURN_REASON ,
								UDC.DRDL01 AS DRDL01 ,
								UDC.DRDL01 AS ROUTE ,
								SUBSTRING(UDC.DRSPHD, 3, 2) AS DRSPHD
						FROM	O_ORDER_CONFIRM_D OCD
								LEFT JOIN O_ORDER_CONFIRM_H OCH ON OCD.CUST_PO = OCH.CUST_PO
								LEFT JOIN O_F0005 UDC ON UDC.DRKY = OCD.WEEK
								LEFT JOIN O_SHIPTO OST ON OCH.SHIPTO_CD = OST.SHIPTO_CD
						WHERE	OCH.REQ_NO = '101781702410224'
						AND		ISNULL(OCD.OCD_STATUSCD, ' ') != '03'
					) XX
		) S

;




--SELECT * FROM ( SELECT ROW_NUMBER() OVER( ORDER BY (SELECT 1) ) AS ROWNUM , XX.* FROM ( SELECT * FROM CONFIG ) XX ) S 


--243Q0038(String), 1(String)

/* eorder.o_qmsorder.getQmsPopMastList */
SELECT
		A.* ,
		CASE
			WHEN (
					SELECT
							COUNT(*)
					FROM	(
								SELECT
										QMS_ID, ORDERNO
								FROM	QMS_ORD_DETL
								GROUP BY QMS_ID, ORDERNO
							) Q
					WHERE	Q.QMS_ID = A.QMS_ID
				) > 1 THEN 'N'
			ELSE 'Y'
		END AS QMS_SPLIT_YN ,
		B.CUST_NM , B.ADD1 + ' ' + B.ADD2 + B.ADD3 + B.ADD4 AS CUST_ADDR ,
		dbo.SF_GETQMSBIZNO(B.TAX_ID) AS CUST_BIZ_NO ,
		B.ZIP_CD , B.SALESREP_CD , B.SALESREP_NM , B.TEAM_CD , B.TEAM_NM ,
		B.MAILING_NM , dbo.SF_GETQMSACTIVEYN(QMS_ID) AS ACTIVEYN
FROM	QMS_ORD_MAST A
		LEFT JOIN O_CUSTOMER B
				ON A.CUST_CD = B.CUST_CD
WHERE	A.QMS_ID = '20243Q0038'
AND		A.QMS_SEQ = 1

;



/* eorder.o_qmsorder.getQmsPopDetlGridList */
SELECT
		/*ROWNUM RR,*/
		XX.* ,
		B.QMS_ID, B.QMS_SEQ , B.QMS_REMARK , B.QMS_DETL_ID ,
		B.QMS_ID + '-' + CONVERT(VARCHAR, B.QMS_SEQ) AS QMS_ORD_NO ,
		(
			SELECT
					CASE
						WHEN COUNT(Q.QMS_ORD_QTY) > 0 THEN SUM(Q.QMS_ORD_QTY)
						ELSE 0
					END
			FROM	QMS_ORD_DETL Q , QMS_ORD_MAST M
			WHERE	Q.QMS_ID = M.QMS_ID
			AND		Q.QMS_SEQ = M.QMS_SEQ
			AND		Q.DELETEYN = 'N'
			AND		M.DELETEYN = 'N'
			AND		Q.ORDERNO = XX.ORDERNO
			AND		Q.LINE_NO = XX.LINE_NO
			AND		Q.ITEM_CD = XX.ITEM_CD
			AND		Q.LOTNO = XX.LOTN
		) AS QMS_ORD_BALANCE ,
		CASE
			WHEN ISNULL(B.QMS_ORD_QTY, 0) = 0 THEN XX.ORDER_QTY - (
																		SELECT
																				CASE
																					WHEN COUNT(Q.QMS_ORD_QTY) > 0 THEN SUM(Q.QMS_ORD_QTY)
																					ELSE 0
																				END
																		FROM	QMS_ORD_DETL Q , QMS_ORD_MAST M
																		WHERE	Q.QMS_ID = M.QMS_ID
																		AND		Q.QMS_SEQ = M.QMS_SEQ
																		AND		Q.DELETEYN = 'N'
																		AND		M.DELETEYN = 'N'
																		AND		Q.ORDERNO = XX.ORDERNO
																		AND		Q.LINE_NO = XX.LINE_NO
																		AND		Q.ITEM_CD = XX.ITEM_CD
																		AND		Q.LOTNO = XX.LOTN
																	)
			ELSE B.QMS_ORD_QTY
		END AS QMS_ORD_QTY ,
		CASE
			WHEN (
					SELECT
							COUNT(*)
					FROM	(
								SELECT QMS_ID, ORDERNO FROM QMS_ORD_DETL GROUP BY QMS_ID, ORDERNO
							) Q
					WHERE	Q.QMS_ID = A.QMS_ID
				) > 1 THEN 'N'
			ELSE 'Y'
		END AS QMS_SPLIT_YN
FROM	(
			SELECT
					ORDERNO, LINE_NO , ITEM_CD, ORDERTY , CUST_PO, CUST_NM,
					CONCAT(CONCAT(CONCAT(CONCAT(SUBSTRING(ORDER_DT, 0, 4), '-'), SUBSTRING(ORDER_DT, 5, 2)), '-'), SUBSTRING(ORDER_DT, 7, 2)) AS ORDER_DT,
					CONCAT(CONCAT(CONCAT(CONCAT(SUBSTRING(ACTUAL_SHIP_DT, 0, 4), '-'), SUBSTRING(ACTUAL_SHIP_DT, 5, 2)), '-'), SUBSTRING(ACTUAL_SHIP_DT, 7, 2)) AS ACTUAL_SHIP_DT,
					SHIPTO_NM, RTRIM(CONCAT(ADD1, ADD2)) AS ADDR, ITEM_DESC, LOTN,
					ORDER_QTY, UNIT, SALESREP_NM
			FROM	qms_salesorder SO
		) XX , QMS_ORD_MAST A , QMS_ORD_DETL B
WHERE	A.QMS_ID = B.QMS_ID
AND		A.QMS_SEQ = B.QMS_SEQ
AND		B.ORDERNO = XX.ORDERNO
AND		B.LINE_NO = XX.LINE_NO
AND		A.QMS_ID = '20243Q0038'
AND		A.QMS_SEQ = 1

;



/* eorder.o_qmsorder.getQmsFireproofList */
SELECT
		A.KEYCODE , A.FIREPROOFTYPE , A.FIRETIME , A.FILENAME ,
		CEILING((
					SELECT COUNT(*) FROM O_FIREPROOFMASTER F WHERE F.FIRETIME = A.FIRETIME AND F.ACTIVE = 'Y' ) / 4
				) AS ROWSPAN_CNT ,
		ROW_NUMBER() OVER (PARTITION BY A.FIRETIME ORDER BY A.KEYCODE ASC) AS RNUM ,
		ROW_NUMBER() OVER ( ORDER BY A.KEYCODE ASC) AS RCNT ,
		(
			SELECT
					COUNT(F.FIRETIME)
			FROM	O_FIREPROOFMASTER F
			WHERE	F.ACTIVE = 'Y'
		) AS RLAST ,
		CASE
			WHEN DENSE_RANK() OVER (PARTITION BY A.FIRETIME ORDER BY A.KEYCODE DESC) = 1 THEN 'Y'
			ELSE 'N'
		END AS LAST_YN ,
		CASE
			WHEN (B.KEYCODE IS NOT NULL AND B.DELETEYN = 'N') THEN 'Y'
			ELSE 'N'
		END AS CHK_YN
FROM	O_FIREPROOFMASTER A
		LEFT OUTER JOIN QMS_ORD_FRCN B
				ON A.KEYCODE = B.KEYCODE
				AND B.QMS_ID = '20243Q0038'
				AND B.QMS_SEQ = 1
WHERE	A.ACTIVE = 'Y'
ORDER BY A.FIRETIME, A.DISPLAYORDER

;




--20240301(String), 20240930(String), 18149847(String), 1(Integer), 15(Integer)


/* eorder.o_qmsorder.cnt */
SELECT
		COUNT(*)
FROM	qms_salesorder SO
		LEFT JOIN O_ITEM_NEW OIN
				ON OIN.ITEM_CD = SO.ITEM_CD /*2024-09-30 hsg LINE_TY에 'Y'값이 없어 죠회가 되지 않아. LEFT JOIN 시 조건을 걸었음 */
				and OIN.LINE_TY = 'Y'
WHERE	1 = 1
	/*2024-09-30 hsg LINE_TY에 'Y'값이 없어 죠회가 되지 않아. LEFT JOIN 시로 취치를 옮김 */
	/* AND OIN.LINE_TY = 'Y' */
AND		NOT(SO.STATUS1 = '980')
AND		SO.STATUS2 >= '620'
AND		OIN.SALES_CD3 IN ('DAP11400', 'DAP11500', 'DAP11600', 'DAP11700', 'DAP12400', 'DAP12500', 'DAP12800', 'DAP12900', 'DAP13000')
AND		SO.ACTUAL_SHIP_DT >= '20240301'
AND		SO.ACTUAL_SHIP_DT <= '20240930'
AND		SO.ORDERNO LIKE '%' + '18149847' + '%'

;




/* eorder.o_qmsorder.list */
SELECT
		/*+ HASH(table) */
		*
FROM	(
			SELECT
					ROW_NUMBER() OVER( ORDER BY XX.ORDERNO DESC, XX.LINE_NO ASC ) AS ROWNUM ,
					XX.* ,
					CASE
						WHEN PRE1 = 'Y' AND PRE2 = 'Y' /* 사전입력 완료 */ THEN '사전'
						WHEN PRE1 = 'Y' AND PRE2 = 'N' /* 사전입력중 */ THEN '사전'
						ELSE '사후' /* 사후입력 대상 */
					END AS QMS_STEP
			FROM	(
						SELECT
								dbo.Sf_getpreorderyn(SO.cust_po) AS PRE1 ,
								dbo.Sf_getpreqtyyn(SO.cust_po) AS PRE2 ,
								ORDERNO, LINE_NO ,
								dbo.SF_GETQMSID(ORDERNO, LINE_NO)AS QMS_ARR ,
								dbo.SF_GETQMSID(ORDERNO, LINE_NO)AS QMS_ARR_TXT ,
								CASE
									WHEN (CONVERT(DECIMAL, dbo.SF_GETPREQTY(SO.cust_po)) >= CONVERT(DECIMAL, SO.ORDER_QTY)
											AND dbo.Sf_getpreorderyn(SO.cust_po) = 'Y'
											AND dbo.Sf_getpreqtyyn(SO.cust_po) = 'Y')
										THEN CONVERT(DECIMAL, SO.ORDER_QTY)
									WHEN dbo.Sf_getpreorderyn(SO.cust_po) = 'Y' THEN CONVERT(DECIMAL, dbo.SF_GETPREQTY(SO.cust_po))
									ELSE CONVERT(DECIMAL, dbo.Sf_getqmsqty(orderno, line_no))
								END AS QMS_ARR_QTY ,
								CASE
									WHEN ORDER_QTY = dbo.SF_GETQMSQTY(ORDERNO, LINE_NO) THEN '완료'
									ELSE '미완료'
								END AS QMS_STATUS ,
								dbo.SF_GETQMSSHIPTO(ORDERNO, LINE_NO)AS QMS_ARR_SHIPTO ,
								dbo.SF_GETMAILYN(ORDERNO, LINE_NO) AS MAIL_YN ,
								dbo.SF_GETFILEYN(ORDERNO, LINE_NO) AS FILE_YN ,
								SO.ITEM_CD , ORDERTY , CUST_PO , CUST_CD , CUST_NM ,
								dbo.SF_GETQMSQUARTER(ACTUAL_SHIP_DT) AS ACTUAL_SHIP_QUARTER ,
								dbo.SF_GETQMSACTIVEYN(dbo.SF_GETQMSQUARTER(ACTUAL_SHIP_DT)) AS ACTIVEYN ,
								CONCAT(CONCAT(CONCAT(CONCAT(SUBSTRING(ORDER_DT, 0, 4), '-'), SUBSTRING(ORDER_DT, 5, 2)), '-'), SUBSTRING(ORDER_DT, 7, 2)) AS ORDER_DT ,
								CONCAT(CONCAT(CONCAT(CONCAT(SUBSTRING(ACTUAL_SHIP_DT, 0, 4), '-'), SUBSTRING(ACTUAL_SHIP_DT, 5, 2)), '-'), SUBSTRING(ACTUAL_SHIP_DT, 7, 2)) AS ACTUAL_SHIP_DT ,
								SHIPTO_CD, SHIPTO_NM, RTRIM(CONCAT(ADD1, ADD2)) AS ADDR, ITEM_DESC, LOTN, ORDER_QTY, UNIT, SALESREP_NM
						FROM	qms_salesorder SO
								LEFT JOIN O_ITEM_NEW OIN
										ON OIN.ITEM_CD = SO.ITEM_CD /*2024-09-30 hsg LINE_TY에 'Y'값이 없어 죠회가 되지 않아. LEFT JOIN 시 조건을 걸었음 */
										AND OIN.LINE_TY = 'Y'
						WHERE	1 = 1
						/*2024-09-30 hsg LINE_TY에 'Y'값이 없어 죠회가 되지 않아. LEFT JOIN 시로 취치를 옮김 */
						/* AND OIN.LINE_TY = 'Y' */
						AND NOT(SO.STATUS1 = '980')
						AND SO.STATUS2 >= '620'
						AND OIN.SALES_CD3 IN ('DAP11400', 'DAP11500', 'DAP11600', 'DAP11700', 'DAP12400', 'DAP12500', 'DAP12800', 'DAP12900', 'DAP13000')
						AND SO.ACTUAL_SHIP_DT >= '20240301'
						AND SO.ACTUAL_SHIP_DT <= '20240930'
						AND SO.ORDERNO LIKE '%' + '18149847' + '%'
					) XX
		) S
WHERE	ROWNUM BETWEEN 1 AND 30

;






--18149847	2000

-- CREATE FUNCTION [dbo].[SF_GETQMSID]
-- (
   -- @IN_ORDERNO varchar(max),
   -- @IN_LINENO varchar(max)
-- )
SELECT
		x.ARR_NAME
FROM	(
			SELECT
					STUFF( (A.QMS_ID+'-'+ CONVERT(VARCHAR(100), A.QMS_SEQ)),  1, 2, '' ) AS ARR_NAME
			FROM	QMS_ORD_MAST A
					LEFT JOIN QMS_ORD_DETL B ON  A.QMS_ID = B.QMS_ID  AND A.QMS_SEQ = B.QMS_SEQ
			WHERE	B.ORDERNO = 18149847
			AND		B.LINE_NO  = 2000
			AND		A.DELETEYN = 'N'
		) X
;



			SELECT
--					(A.QMS_ID+'-'+ CONVERT(VARCHAR(100), A.QMS_SEQ)) as aaa
					STUFF( (A.QMS_ID+'-'+ CONVERT(VARCHAR(100), A.QMS_SEQ)),  1, 0, '' ) as bbb
			FROM	QMS_ORD_MAST A
					LEFT JOIN QMS_ORD_DETL B ON  A.QMS_ID = B.QMS_ID  AND A.QMS_SEQ = B.QMS_SEQ
			WHERE	B.ORDERNO = 18149847
			AND		B.LINE_NO  = 2000
			AND		A.DELETEYN = 'N'

;


SELECT
		*
FROM	QMS_ORD_MAST
;



CREATE FUNCTION [dbo].[SF_GETQMSID_YYYY] 
( 
   @IN_ORDERNO varchar(max),
   @IN_LINENO varchar(max)
)
RETURNS varchar(max)
AS 
	BEGIN

		DECLARE  @return_Val varchar(max)

		SELECT @return_Val = x.ARR_NAME
		FROM (
			SELECT 
			STUFF(
				(A.QMS_ID+'-'+ CONVERT(VARCHAR(100), A.QMS_SEQ)),  1, 0, ''  
				) AS ARR_NAME
			FROM QMS_ORD_MAST A
			LEFT JOIN QMS_ORD_DETL B ON  A.QMS_ID = B.QMS_ID  AND A.QMS_SEQ = B.QMS_SEQ
			WHERE B.ORDERNO = @IN_ORDERNO
				AND B.LINE_NO  = @IN_LINENO
				AND A.DELETEYN = 'N'
		) X;


		RETURN @return_Val

	END
;














