UPDATE	O_ORDER_CONFIRM_H
SET		SALESREP_NM = (
						SELECT	OS.SALESREP_NM
						FROM	O_SALESORDER OS
						WHERE	OS.CUST_PO = O_ORDER_CONFIRM_H.CUST_PO
					  ),
		SALESREP_CD = (
						SELECT	OS.SALESREP_CD
						FROM	O_SALESORDER OS
						WHERE	OS.CUST_PO = O_ORDER_CONFIRM_H.CUST_PO
					  )
WHERE	EXISTS (
					SELECT	1
					FROM	O_SALESORDER OS
					WHERE	OS.CUST_PO = O_ORDER_CONFIRM_H.CUST_PO
				)
;








