

/* *********** 전달받은 쿼리 *********** */
;


UPDATE O_ORDER_CONFIRM_H
SET
    SALESREP_NM = (
        SELECT OS.SALESREP_NM
        FROM O_SALESORDER OS
        WHERE OS.CUST_PO = O_ORDER_CONFIRM_H.CUST_PO
    ),
    SALESREP_CD = (
        SELECT OS.SALESREP_CD
        FROM O_SALESORDER OS
        WHERE OS.CUST_PO = O_ORDER_CONFIRM_H.CUST_PO
    )
WHERE EXISTS (
    SELECT 1
    FROM O_SALESORDER OS
    WHERE OS.CUST_PO = O_ORDER_CONFIRM_H.CUST_PO
)
;





/* *********** UPDATE 문 *********** */


SELECT	*
FROM	O_ORDER_CONFIRM_H OCH
		INNER JOIN O_SALESORDER OS
                ON OS.CUST_PO = OCH.CUST_PO
WHERE	1 = 1
AND		OCH.SALESREP_NM IS NULL
		OR	OCH.SALESREP_CD IS NULL
;




SELECT	OCH.REQ_NO, OCH.CUST_PO, OCH.SALESREP_CD, OCH.SALESREP_NM
FROM	O_ORDER_CONFIRM_H OCH
		LEFT OUTER JOIN O_SALESORDER OS
                ON OS.CUST_PO = OCH.CUST_PO
WHERE	1 = 1
--AND		OCH.SALESREP_NM IS NOT NULL
AND		OCH.SALESREP_CD IS NULL
;


--SELECT	OS.CUST_PO, OCH.*
SELECT	COUNT(*)
FROM	O_ORDER_CONFIRM_H OCH
		LEFT OUTER JOIN O_SALESORDER OS
                ON OCH.CUST_PO = OS.CUST_PO
WHERE	1 = 1
--AND		OCH.SA
;


SELECT
		*
  FROM	O_ORDER_CONFIRM_H OCH
 WHERE	1 = 1
   AND	CUST_PO = '100220402501092-1'
--GROUP BY 
--ORDER BY 
;


SELECT
		CUST_PO, COUNT(*) AS CNT
  FROM	O_ORDER_CONFIRM_H os
 WHERE	1 = 1
--   AND	
GROUP BY CUST_PO
HAVING COUNT(*) > 1
--ORDER BY 
;



SELECT
		*
  FROM	O_SALESORDER OS
 WHERE	1 = 1
   AND	OS.CUST_PO = '100220402501091'
--GROUP BY 
--ORDER BY 
;


SELECT
		CUST_PO, COUNT(*) AS CNT
  FROM	O_SALESORDER os
 WHERE	1 = 1
GROUP BY CUST_PO
	HAVING COUNT(*) > 1
;


SELECT	CUST_PO, MAX(SALESREP_CD) AS SALESREP_CD, MAX(SALESREP_NM) AS SALESREP_NM
		, PATINDEX('%[0-9]%', CUST_PO) AS AAA
		, TRY_CAST(CUST_PO AS FLOAT) AS BBB
FROM	O_SALESORDER OS
WHERE	1 = 1
--AND		TRY_CAST(CUST_PO AS INT) IS NULL
--AND		ISNUMERIC(CUST_PO) = 0
--AND		CUST_PO LIKE '%[0-9\-]%'
--AND		CUST_PO LIKE '%[^0-9][\-][0-9]%'
AND		CUST_PO NOT LIKE '%[a-zA-Z가-힣]%'
AND		LEN(CUST_PO) >= 15
GROUP BY CUST_PO
	HAVING COUNT(*) = 1
;



SELECT	CUST_PO, MAX(SALESREP_CD) AS SALESREP_CD, MAX(SALESREP_NM) AS SALESREP_NM
FROM	O_SALESORDER OS
WHERE	1 = 1
AND		CUST_PO NOT LIKE '%[a-zA-Z가-힣]%' -- 영어나 한글이 포함되지 않은 경우
AND		LEN(CUST_PO) >= 15	-- 길이가 15 이상인 것
GROUP	BY
		CUST_PO
;


SELECT
--		CUST_PO, MAX(SALESREP_CD) AS SALESREP_CD, MAX(SALESREP_NM) AS SALESREP_NM
		ROW_NUMBER() OVER(PARTITION BY CUST_PO ORDER BY CUST_PO ASC) AS ROWNUM,
		CUST_PO, SALESREP_CD, SALESREP_NM
FROM	O_SALESORDER OS
WHERE	1 = 1
AND		CUST_PO NOT LIKE '%[a-zA-Z가-힣]%' -- 영어나 한글이 포함되지 않은 경우
AND		LEN(CUST_PO) >= 15	-- 길이가 15 이상인 것
;







/* *********** UPDATE *********** */
;

UPDATE	OCH
SET		SALESREP_NM = OS.SALESREP_NM,
		SALESREP_CD = OS.SALESREP_CD
FROM	O_ORDER_CONFIRM_H OCH
		INNER JOIN O_SALESORDER OS
                ON OS.CUST_PO = OCH.CUST_PO
WHERE	1 = 1
AND		OCH.SALESREP_CD IS NULL
-- AND 	OCH.SALESREP_CD IS NULL
;




/* *********** 최종 전전전 일까? *********** */
;

UPDATE	OCH
SET		SALESREP_NM = OS.SALESREP_NM,
		SALESREP_CD = OS.SALESREP_CD
FROM	O_ORDER_CONFIRM_H OCH
		INNER JOIN  O_SALESORDER OS
                ON  OS.CUST_PO = OCH.CUST_PO
                AND	OS.CUST_PO NOT LIKE '%[a-zA-Z가-힣]%'
                AND	LEN(OS.CUST_PO) >= 15
WHERE	1 = 1
;



WITH TB AS	(
				SELECT	CUST_PO, MAX(SALESREP_CD) AS SALESREP_CD, MAX(SALESREP_NM) AS SALESREP_NM
				FROM	O_SALESORDER OS
				WHERE	1 = 1
--				AND		CUST_PO LIKE '%[0-9][\-][0-9]%'
				AND		CUST_PO NOT LIKE '%[a-zA-Z가-힣]%' -- 영어나 한글이 포함되지 않은 경우
				AND		LEN(CUST_PO) >= 15	-- 길이가 15 이상인 것
				GROUP	BY
						CUST_PO
--				HAVING	COUNT(*) = 1
			)
UPDATE	OCH
SET		SALESREP_NM = OS.SALESREP_NM,
		SALESREP_CD = OS.SALESREP_CD
FROM	O_ORDER_CONFIRM_H OCH
		INNER JOIN  TB OS
                ON  OS.CUST_PO = OCH.CUST_PO
WHERE	1 = 1
AND		OCH.SALESREP_CD IS NULL
;





/* *********** 최종이면 좋겠다. *********** */

WITH TB AS	(
				SELECT
						ROW_NUMBER() OVER(PARTITION BY CUST_PO ORDER BY CUST_PO ASC) AS ROWNUM, -- 중복일 경우 CUST_PO 순으로 순번을 매긴다.
						CUST_PO, SALESREP_CD, SALESREP_NM
				FROM	O_SALESORDER OS
				WHERE	1 = 1
				AND		CUST_PO NOT LIKE '%[a-zA-Z가-힣]%' -- 영어나 한글이 포함되지 않은 경우
				AND		LEN(CUST_PO) >= 15	-- 길이가 15 이상인 것
			)
UPDATE	OCH
SET		SALESREP_NM = OS.SALESREP_NM,
		SALESREP_CD = OS.SALESREP_CD
FROM	O_ORDER_CONFIRM_H OCH
		INNER JOIN  TB OS
                ON  OS.CUST_PO = OCH.CUST_PO
                AND OS.ROWNUM = 1	-- CUST_PO별 순번에서 첫번째 - 1인 것만
WHERE	1 = 1
AND		OCH.SALESREP_CD IS NULL
;






