

/* *********** eorder.config.list  *********** */

	SELECT	*
	  FROM	(
				SELECT
						ROW_NUMBER() OVER( ORDER BY (SELECT 1) ) AS ROWNUM
						, XX.*
				  FROM	( SELECT * FROM CONFIG ) XX
			) S
;


/* *********** eorder.o_cust_order_h.cnt *********** */


	SELECT	COUNT(*)
	  FROM	O_CUST_ORDER_H COH
			LEFT JOIN O_CUSTOMER CU ON COH.CUST_CD = CU.CUST_CD
			LEFT JOIN O_SHIPTO ST ON COH.SHIPTO_CD = ST.SHIPTO_CD
			LEFT JOIN O_USER US_SALES ON CU.SALESREP_CD = US_SALES.USERID
	 WHERE	RTRIM(COH.USERID) = RTRIM('10177560')
	   AND	COH.INDATE >= CONVERT(DATE, '2024-12-20')
	   AND	COH.INDATE < DATEADD(day, 1,CONVERT(DATE, '2024-12-20'))
	   AND	COH.STATUS_CD IN ('99')

;



/* *********** eorder.o_customer.one *********** */

	SELECT
			  CU.*, US.USER_NM, US.AUTHORITY, US.USER_FILE, US.CELL_NO, US.USER_POSITION
			, (SELECT COUNT(*) FROM O_USER WHERE CUST_CD = CU.CUST_CD AND AUTHORITY = 'CO') AS CUSTOMER_USER_CNT
			, (SELECT COUNT(*) FROM O_USER WHERE CUST_CD = CU.CUST_CD AND AUTHORITY = 'CT') AS SHIPTO_USER_CNT
			, (SELECT COUNT(*) FROM O_SHIPTO WHERE CUST_CD = CU.CUST_CD) AS SHIPTO_CNT
			, US2.USER_NM AS CSUSER_NM
			, US2.TEL_NO AS CSUSER_TEL
			, US2.CELL_NO AS CSUSER_CELL
			, US2.USER_FILE AS CSUSER_FILE
			, US2.USER_POSITION AS CSUSER_POSITION
	  FROM	O_CUSTOMER CU
			LEFT JOIN O_USER US ON CU.SALESREP_CD = US.USERID
			LEFT JOIN O_CSSALESMAP CSM ON CU.SALESREP_CD = CSM.SALESUSERID AND CSM.FIXEDYN='Y'
			LEFT JOIN O_USER US2 ON CSM.CSUSERID = US2.USERID
	 WHERE	CU.CUST_CD = '10177560'
;





/* *********** eorder.banner.listForFront *********** */

	SELECT	*
	  FROM	(
				SELECT
						ROW_NUMBER() OVER( /*ORDER BY (SELECT 1)*/ ORDER BY BN_INDATE DESC ) AS ROWNUM
						, *
				  FROM	BANNER
				 WHERE	BN_USEYN = 'Y'
				   AND	BN_TYPE = '3'
			) XX
	 WHERE	ROWNUM <= 10
;





























































