

		/* eorder.o_qmsorder.getQmsPopMastList */
		SELECT
				A.*
				, CASE
						WHEN (
								SELECT	COUNT(*)
								FROM	( SELECT QMS_ID,ORDERNO FROM QMS_ORD_DETL GROUP BY QMS_ID,ORDERNO ) Q
								WHERE	Q.QMS_ID = A.QMS_ID
							 ) > 1 THEN 'N'
						ELSE 'Y'
				  END AS QMS_SPLIT_YN
				, B.CUST_NM
				, B.ADD1 AS CUST_ADDR
				, dbo.SF_GETQMSBIZNO(B.TAX_ID) AS CUST_BIZ_NO
				, B.ZIP_CD
				, B.SALESREP_CD
				, B.SALESREP_NM
				, B.TEAM_CD
				, B.TEAM_NM
				, B.MAILING_NM
				, dbo.SF_GETQMSACTIVEYN(QMS_ID) AS ACTIVEYN
		FROM	QMS_ORD_MAST A
				LEFT JOIN O_CUSTOMER B ON A.CUST_CD = B.CUST_CD
		WHERE	A.QMS_ID = NULL
		  AND	A.DELETEYN = 'N'
;



		/* eorder.o_qmsorder.getQmsPopDetlList */
		SELECT	B.*
		  FROM	QMS_ORD_MAST A , QMS_ORD_DETL B
		 WHERE	A.QMS_ID = B.QMS_ID
		   AND	A.QMS_ID = NULL
		   AND	A.DELETEYN = 'N'
;


		/* eorder.o_qmsorder.getQmsFireproofList */
		SELECT
				A.KEYCODE
			  , A.FIREPROOFTYPE
			  , FORMAT(A.FIRETIME, '0.#') AS FIRETIME
			  , A.FILENAME
			  , CEILING((SELECT COUNT(*) FROM O_FIREPROOFMASTER F WHERE F.FIRETIME = A.FIRETIME AND F.ACTIVE = 'Y' ) / 4) AS ROWSPAN_CNT
			  , ROW_NUMBER() OVER (PARTITION BY A.FIRETIME ORDER BY A.KEYCODE ASC) AS RNUM
			  , ROW_NUMBER() OVER (ORDER BY A.KEYCODE ASC) AS RCNT
			  , (SELECT COUNT(F.FIRETIME) FROM O_FIREPROOFMASTER F WHERE F.ACTIVE = 'Y') AS RLAST
			  , CASE WHEN DENSE_RANK() OVER (PARTITION BY A.FIRETIME ORDER BY A.KEYCODE DESC) = 1 THEN 'Y' ELSE 'N' END AS LAST_YN
			  , CASE WHEN (B.KEYCODE IS NOT NULL AND B.DELETEYN='N') THEN 'Y' ELSE 'N' END AS CHK_YN
		  FROM	O_FIREPROOFMASTER A
				LEFT OUTER JOIN QMS_ORD_FRCN B ON A.KEYCODE = B.KEYCODE AND B.QMS_ID	 = NULL AND B.QMS_SEQ = 1
		 WHERE	A.ACTIVE = 'Y'
		 ORDER BY A.FIRETIME,A.DISPLAYORDER
;






		/* eorder.o_qmsorder.getQmsPopMastList */
		SELECT
				A.*
			  , CASE
					WHEN (
							SELECT	COUNT(*)
							  FROM	( SELECT QMS_ID,ORDERNO FROM QMS_ORD_DETL GROUP BY QMS_ID,ORDERNO) Q
							 WHERE	Q.QMS_ID = A.QMS_ID
						 ) > 1 THEN 'N'
					ELSE 'Y'
				END AS QMS_SPLIT_YN
			  , B.CUST_NM
			  , B.ADD1 AS CUST_ADDR
			  , dbo.SF_GETQMSBIZNO(B.TAX_ID) AS CUST_BIZ_NO
			  , B.ZIP_CD
			  , B.SALESREP_CD
			  , B.SALESREP_NM
			  , B.TEAM_CD
			  , B.TEAM_NM
			  , B.MAILING_NM
			  , dbo.SF_GETQMSACTIVEYN(QMS_ID) AS ACTIVEYN
		  FROM	QMS_ORD_MAST A
				LEFT JOIN O_CUSTOMER B ON A.CUST_CD = B.CUST_CD
		 WHERE	A.QMS_ID = '20243Q0037'
		   AND	A.QMS_SEQ = '1'
;


/* eorder.o_qmsorder.getQmsPopDetlList */
		SELECT	B.*
		  FROM	QMS_ORD_MAST A ,QMS_ORD_DETL B
		 WHERE	A.QMS_ID = B.QMS_ID
		   AND	A.QMS_ID = '20243Q0037'
		   AND	A.QMS_SEQ = '1'
;



/* eorder.o_qmsorder.getQmsFireproofList */
		SELECT
				A.KEYCODE
			  , A.FIREPROOFTYPE
			  , FORMAT(A.FIRETIME, '0.#') AS FIRETIME
			  , A.FILENAME
			  , CEILING((SELECT COUNT(*) FROM O_FIREPROOFMASTER F WHERE F.FIRETIME = A.FIRETIME AND F.ACTIVE = 'Y' ) / 4) AS ROWSPAN_CNT
			  , ROW_NUMBER() OVER (PARTITION BY A.FIRETIME ORDER BY A.KEYCODE ASC) AS RNUM
			  , ROW_NUMBER() OVER (ORDER BY A.KEYCODE ASC) AS RCNT
			  , (SELECT COUNT(F.FIRETIME) FROM O_FIREPROOFMASTER F WHERE F.ACTIVE = 'Y') AS RLAST
			  , CASE WHEN DENSE_RANK() OVER (PARTITION BY A.FIRETIME ORDER BY A.KEYCODE DESC) = 1 THEN 'Y' ELSE 'N' END AS LAST_YN
			  , CASE WHEN (B.KEYCODE IS NOT NULL AND B.DELETEYN='N') THEN 'Y' ELSE 'N' END AS CHK_YN
		  FROM	O_FIREPROOFMASTER A
				LEFT OUTER JOIN QMS_ORD_FRCN B ON A.KEYCODE = B.KEYCODE AND B.QMS_ID = '20243Q0037' AND B.QMS_SEQ = '1'
		 WHERE 	A.ACTIVE = 'Y'
		 ORDER BY A.FIRETIME,A.DISPLAYORDER
;




/* eorder.o_qmsorder.getQmsPopDetlGridList */
		SELECT /*ROWNUM RR,*/
				XX.* ,B.QMS_ID, B.QMS_SEQ ,B.QMS_REMARK ,B.QMS_DETL_ID ,B.QMS_ID +'-'+ CONVERT(VARCHAR, B.QMS_SEQ) AS QMS_ORD_NO
			  ,	(
					SELECT
							CASE WHEN COUNT(Q.QMS_ORD_QTY) > 0 THEN SUM(Q.QMS_ORD_QTY) ELSE 0 END
					  FROM	QMS_ORD_DETL Q , QMS_ORD_MAST M
					 WHERE	Q.QMS_ID = M.QMS_ID AND Q.QMS_SEQ = M.QMS_SEQ AND Q.DELETEYN = 'N' AND M.DELETEYN = 'N'
					   AND	Q.ORDERNO = XX.ORDERNO AND Q.LINE_NO = XX.LINE_NO AND Q.ITEM_CD = XX.ITEM_CD AND Q.LOTNO = XX.LOTN
				) AS QMS_ORD_BALANCE
			  ,	CASE
					WHEN ISNULL(B.QMS_ORD_QTY,0) = 0 THEN XX.ORDER_QTY - (
																			SELECT
																					CASE
																						WHEN COUNT(Q.QMS_ORD_QTY) > 0 THEN SUM(Q.QMS_ORD_QTY)
																						ELSE 0
																					END
																			  FROM	QMS_ORD_DETL Q , QMS_ORD_MAST M
																			 WHERE	Q.QMS_ID = M.QMS_ID
																			   AND	Q.QMS_SEQ = M.QMS_SEQ
																			   AND	Q.DELETEYN = 'N'
																			   AND	M.DELETEYN = 'N'
																			   AND	Q.ORDERNO = XX.ORDERNO
																			   AND	Q.LINE_NO = XX.LINE_NO
																			   AND	Q.ITEM_CD = XX.ITEM_CD
																			   AND	Q.LOTNO = XX.LOTN
																		   )
					ELSE B.QMS_ORD_QTY
				END AS QMS_ORD_QTY
			  ,	CASE
					WHEN	(
								SELECT	COUNT(*)
								  FROM	( SELECT QMS_ID,ORDERNO FROM QMS_ORD_DETL GROUP BY QMS_ID,ORDERNO) Q
								 WHERE	Q.QMS_ID = A.QMS_ID
							) > 1 THEN 'N'
					ELSE 'Y'
				END AS QMS_SPLIT_YN
		  FROM	(
					SELECT
							ORDERNO,LINE_NO ,ITEM_CD,ORDERTY , CUST_PO, CUST_NM,
							CONCAT(CONCAT(CONCAT(CONCAT(SUBSTRING(ORDER_DT, 0,4), '-'), SUBSTRING(ORDER_DT, 5, 2)), '-'), SUBSTRING(ORDER_DT, 7, 2)) AS ORDER_DT,
							CONCAT(CONCAT(CONCAT(CONCAT(SUBSTRING(ACTUAL_SHIP_DT, 0,4), '-'), SUBSTRING(ACTUAL_SHIP_DT, 5, 2)), '-'), SUBSTRING(ACTUAL_SHIP_DT, 7, 2)) AS ACTUAL_SHIP_DT,
							SHIPTO_NM, RTRIM(CONCAT(ADD1, ADD2)) AS ADDR, ITEM_DESC, LOTN, ORDER_QTY, UNIT, SALESREP_NM
					  FROM	qms_salesorder SO
				) XX
			  ,	QMS_ORD_MAST A
			  ,	QMS_ORD_DETL B
		 WHERE	A.QMS_ID	= B.QMS_ID
		   AND	A.QMS_SEQ 	= B.QMS_SEQ
		   AND	B.ORDERNO 	= XX.ORDERNO
		   AND	B.LINE_NO 	= XX.LINE_NO
		   AND	A.QMS_ID	= '20243Q0037'
		   AND	A.QMS_SEQ	= '1'
;







